# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""Frozen record of what the dispatcher EMITS and RETURNS, per outcome.

Companion to tests/test_dispatch_kwargs_baseline.py, taken for the same reason and at the
same moment: `execute_tool` is about to be split into a caller-agnostic funnel plus the
chat-turn machinery, and "nothing changed" has to be a measurement.

The kwargs baseline covers what reaches a tool. This one covers everything after that
decision: which events fire, in which order, with which `ok` flag, and which recognisable
prefix comes back. Those are a contract, not incidental - `docs/OBSERVABILITY.md` publishes
the event schema, `vaf/markers.py` publishes the prefixes, and the Whare Wananga retry lane
keys off "Tool Error:". A reordering here is invisible in a diff and breaks consumers.

THREE THINGS IT EXISTS TO CATCH, each a place where the obvious cut goes quietly wrong:

1. Precedence. Invalid arguments and a running same-type sub-agent can be true at once, and
   the invalid-args branch is checked first. `dup_guard_alone` proves the guard really fires
   on its own; `invalid_args_beats_dup_guard` proves that when BOTH hold, the schema error is
   what comes back. Without the first scenario the second would only prove that invalid args
   beat nothing.

2. Silence is part of the contract. A hard policy block emits NOTHING - no tool_start, no
   tool_end - and the chat gates return their message the same way. A funnel that emitted a
   tool_start before evaluating policy would look harmless and would tell every event
   consumer that a blocked tool ran.

3. The refusal shape. Under `VAF_NONINTERACTIVE` a gated tool emits `gate_required` and then
   stops: no `gate_decision`, no tool_start, no tool_end. That asymmetry is documented in
   OBSERVABILITY.md and is easy to "tidy up" into a symmetric pair.

The `ok` flag is pinned with the events because it is a DISPATCH-level judgement, not tool
semantics: it is False only for "Tool Error:" and unknown-tool. A tool returning an error
string of its own still reports ok=True, and that is deliberate.

Scenarios are measured, never typed; the shape of a return is pinned by its prefix rather
than its prose, so wording can improve without the guard going off.
"""
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from vaf.core.agent import Agent
from vaf.tools.base import BaseTool

SCOPE = "deadbeef-0000-0000-0000-000000000000"   # synthetic; never a real scope UUID


# Generated by measurement against the unchanged dispatcher - never edit by hand.
EVENT_BASELINE = {
    "dup_guard_alone": {
        "events": [("tool_start", None), ("tool_end", True)],
        "returns": "<plain>",
        "truncated": False,
    },
    "gate_refused_noninteractive": {
        "events": [("gate_required", None)],
        "returns": "[ERROR]",
        "truncated": False,
    },
    "invalid_args": {
        "events": [("tool_start", None), ("tool_end", False)],
        "returns": "Tool Error:",
        "truncated": False,
    },
    "invalid_args_beats_dup_guard": {
        "events": [("tool_start", None), ("tool_end", False)],
        "returns": "Tool Error:",
        "truncated": False,
    },
    "ok": {
        "events": [("tool_start", None), ("tool_end", True)],
        "returns": "<plain>",
        "truncated": False,
    },
    "plan_gate": {
        "events": [],
        "returns": "[PLAN REQUIRED]",
        "truncated": False,
    },
    "policy_admin_only": {
        "events": [],
        "returns": "Security Error:",
        "truncated": False,
    },
    "policy_channel": {
        "events": [],
        "returns": "Security Error:",
        "truncated": False,
    },
    "self_supervised": {
        "events": [("tool_start", None), ("tool_end", True)],
        "returns": "<plain>",
        "truncated": False,
    },
    "tool_raises": {
        "events": [("tool_start", None), ("tool_end", False)],
        "returns": "Tool Error:",
        "truncated": False,
    },
    "truncation": {
        "events": [("tool_start", None), ("tool_end", True)],
        "returns": "<plain>",
        "truncated": True,
    },
    "unknown_tool": {
        "events": [("tool_start", None), ("tool_end", False)],
        "returns": "Error: Unknown tool",
        "truncated": False,
    },
}


class _Probe(BaseTool):
    name = "probe"
    description = "probe"
    permission_level = "read"
    parameters = {"type": "object", "properties": {"x": {"type": "string"}}}

    def __init__(self, fn=None, **attrs):
        super().__init__()
        self._fn = fn or (lambda **kw: "OK")
        for k, v in attrs.items():
            setattr(self, k, v)

    def run(self, **kwargs):
        return self._fn(**kwargs)


def _tool(name, fn=None, **attrs):
    t = _Probe(fn, **attrs)
    t.name = name
    return t


def _fake(tools, events, **over):
    base = dict(
        tools={t.name: t for t in tools}, _event_sink=events.append,
        _allow_once_tools={t.name for t in tools}, _noninteractive=True,
        _current_turn_thinking_mode=False, _current_chat_source="web",
        current_session_id=None, _current_user_scope_id=SCOPE, _current_user_role="admin",
        _current_username="tenant", _run_kind="chat", _ww_training=False,
        _active_tools=set(), _turn_ran_progress_tool=False, _session_workspace=None,
        history=[], main_persistence=None, _record_tool_used=lambda n: None,
        _plan_gate_decision=lambda n, t, tool_args=None: None,
        _working_memory_note_gate=lambda tool_args: None,
        _proactive_reply_gate_decision=lambda n, t, a: None,
        _ask_first_gate_decision=lambda n, t: None,
        get_live_session_subagents=lambda: [], _extract_subagent_goal=lambda a: "",
        model_display_name="probe",
    )
    base.update(over)
    return SimpleNamespace(**base)


_PREFIXES = ("Security Error:", "Tool Error:", "Error: Unknown tool", "[CANCELLED]",
             "[ERROR]", "[VAF_TOOL_TIMEOUT]", "[VAF_TOOL_STOPPED]", "[PLAN REQUIRED]",
             "[BLOCKED]", "[CONFIRM REQUIRED]", "[AWAITING USER]", "Error:")


def _shape(s):
    s = str(s)
    for p in _PREFIXES:
        if s.startswith(p):
            return p
    return "<plain>"


def _run(tools, call, pre_approved=True, config=None, **over):
    """Run one dispatch under a fully controlled environment.

    Every input the dispatcher consults has to be pinned here, config included. The first
    version of this file patched the trust store but let ``Config`` fall through to whatever
    the developing machine had on disk - and the machine that recorded the baseline happened
    to have ``channel_tools_unrestricted`` turned OFF while the shipped default is ON. So the
    channel scenario measured a blocked call locally and an executed one in CI, and the
    baseline was a fact about one laptop rather than about the code.
    """
    events = []
    fake = _fake(tools, events, **over)
    policy = "always" if pre_approved else "ask"
    settings = dict(config or {})

    def _config_get(key, default=None):
        return settings.get(key, default)

    with patch("vaf.core.trust.get_tool_policy", return_value=policy), \
         patch("vaf.core.trust.is_trusted_dir", return_value=pre_approved), \
         patch("vaf.core.config.Config.get", side_effect=_config_get):
        res = Agent.execute_tool(fake, *call)
    return {
        "events": [(e.get("type"), e.get("ok")) for e in events],
        "returns": _shape(res),
        "truncated": "[Output Truncated." in str(res),
    }


def _boom(**kw):
    raise ValueError("kaputt")


_LIVE_CODER = [{"agent_type": "coding_agent", "task_description": "t", "running_seconds": 60}]
_STRICT = {"type": "object", "properties": {"x": {"type": "string"}}, "required": ["x"]}
_SUB_STRICT = {"type": "object", "properties": {"task": {"type": "string"}},
               "required": ["task"]}

# Each entry builds its scenario; the expected result lives in EVENT_BASELINE above.
SCENARIOS = {
    "ok": lambda: _run([_tool("probe")], ("probe", {})),
    "unknown_tool": lambda: _run([_tool("probe")], ("nope", {})),
    "tool_raises": lambda: _run([_tool("probe", _boom)], ("probe", {})),
    "policy_admin_only": lambda: _run(
        [_tool("probe", admin_only=True)], ("probe", {}), _current_user_role="user"),
    # channel_tools_unrestricted LIFTS the channel block, and its shipped default is ON - so
    # the scenario has to state which side of that it is testing. Here: the block itself.
    "policy_channel": lambda: _run(
        [_tool("probe", channel_restrictions=("telegram",))], ("probe", {}),
        config={"channel_tools_unrestricted": False},
        _current_chat_source="telegram"),
    "plan_gate": lambda: _run(
        [_tool("probe")], ("probe", {}),
        _plan_gate_decision=lambda n, t, tool_args=None: "[PLAN REQUIRED] do a plan"),
    "gate_refused_noninteractive": lambda: _run(
        [_tool("probe", permission_level="dangerous")], ("probe", {}),
        pre_approved=False, _allow_once_tools=set(), _noninteractive=True),
    "invalid_args": lambda: _run([_tool("probe", parameters=_STRICT)], ("probe", {})),
    "truncation": lambda: _run([_tool("probe", lambda **kw: "y" * 5000)], ("probe", {})),
    "dup_guard_alone": lambda: _run(
        [_tool("coding_agent", parameters=_SUB_STRICT)], ("coding_agent", {"task": "t"}),
        get_live_session_subagents=lambda: _LIVE_CODER),
    "invalid_args_beats_dup_guard": lambda: _run(
        [_tool("coding_agent", parameters=_SUB_STRICT)], ("coding_agent", {}),
        get_live_session_subagents=lambda: _LIVE_CODER),
    "self_supervised": lambda: _run([_tool("python_sandbox")], ("python_sandbox", {})),
}


@pytest.mark.parametrize("scenario", sorted(EVENT_BASELINE))
def test_the_dispatch_outcome_is_unchanged(scenario):
    assert scenario in SCENARIOS, f"{scenario} has a frozen result but no way to reproduce it"
    measured = SCENARIOS[scenario]()
    expected = EVENT_BASELINE[scenario]
    assert measured["events"] == expected["events"], (
        f"{scenario}: event stream changed. Order, count and the ok flag are all published "
        f"contract (docs/OBSERVABILITY.md)."
    )
    assert measured["returns"] == expected["returns"], (
        f"{scenario}: the return prefix changed. Callers match on these (vaf/markers.py, the "
        f"Whare Wananga retry lane)."
    )
    assert measured["truncated"] == expected["truncated"], f"{scenario}: truncation changed"


def test_every_scenario_is_frozen():
    """A scenario with no baseline row would run and prove nothing."""
    missing = sorted(set(SCENARIOS) - set(EVENT_BASELINE))
    assert not missing, f"scenarios with no frozen result: {missing}"


def test_a_hard_block_stays_silent():
    """Called out separately because it is the one an eager funnel breaks first: emitting
    tool_start before policy would tell every consumer that a blocked tool ran."""
    for scenario in ("policy_admin_only", "policy_channel", "plan_gate"):
        assert EVENT_BASELINE[scenario]["events"] == [], scenario


def test_invalid_arguments_outrank_the_duplicate_guard():
    """The precedence, spelled out. Read together: the guard does fire on its own, and it
    still loses when the arguments are also invalid."""
    assert EVENT_BASELINE["dup_guard_alone"]["returns"] == "<plain>", (
        "the duplicate guard stopped firing - then the precedence test below proves nothing"
    )
    assert EVENT_BASELINE["invalid_args_beats_dup_guard"]["returns"] == "Tool Error:"
