# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""How far the workflow identity switch reaches, measured rather than argued.

Turning ``workflow_identity_injection`` to "declared" changes who a workflow step acts as,
for a lot of tools at once. That is the point - until it flipped, a saved workflow ran as the
machine owner no matter who started it, so its GitHub calls used the ADMIN's token and its
file writes were confined to nobody - but "a lot at once" is exactly the shape of change that
should not rest on somebody's reading of a 47-line if/elif chain.

So the reach is MEASURED here, by EXECUTING the legacy branch for every registered tool and
comparing against what each tool declares. Two things follow:

1. THE SAFETY PROPERTY: no tool may lose an identity key it had before. The switch is meant
   to widen who gets an identity, never to take one away - a tool that silently stopped
   receiving its scope would start writing into the machine owner's data again, which is the
   bug being fixed, reintroduced by its own fix.
2. THE BLAST RADIUS IS A FROZEN FACT. The list below is generated, never typed. It is not
   here to be admired; it is here so that a tool joining or leaving it shows up as a diff in
   a security-relevant review rather than as silence.

The list is a floor, not a ceiling: adding ``identity_kwargs`` to another tool SHOULD extend
it, and the failure message says so. What must not happen is that it changes unnoticed.
"""
import ast
import importlib
import inspect
import pathlib
import pkgutil
import textwrap

from vaf.tools.base import BaseTool

ENGINE = pathlib.Path(__file__).resolve().parents[1] / "vaf" / "workflows" / "engine.py"


def _declared_by_every_tool(include_empty=False):
    import vaf.tools

    out = {}
    for mod in pkgutil.iter_modules(vaf.tools.__path__):
        try:
            module = importlib.import_module("vaf.tools." + mod.name)
        except Exception:
            continue
        for _, cls in inspect.getmembers(module, inspect.isclass):
            if not (issubclass(cls, BaseTool) and cls is not BaseTool):
                continue
            name = getattr(cls, "name", None)
            if not name:
                continue
            keys = tuple(sorted(set(getattr(cls, "identity_kwargs", ()) or ())))
            if keys or include_empty:
                out[name] = keys
    return out


def _legacy_distribution():
    """Run the historical name-list branch for every tool name and record what it assigns.

    EXECUTED rather than parsed. Two attempts to read this by regular expression produced two
    different wrong answers - one merged a nested ``if`` into its parent branch and invented a
    key, the other overwrote a branch and lost one. The function is the only authority on what
    the function does.
    """
    source = ENGINE.read_bytes().decode()
    lines = source.split(chr(10))
    fn = next(n for n in ast.walk(ast.parse(source))
              if isinstance(n, ast.FunctionDef) and n.name == "_inject_user_scope")
    body = textwrap.dedent(chr(10).join(lines[fn.lineno - 1:fn.end_lineno]))
    namespace = {
        "Dict": dict, "Any": object,
        "self": type("_Ctx", (), {"user_scope_id": "SCOPE", "username": "USER"})(),
        "_identity_mode": lambda: "legacy",
        "_identity_is_declared": lambda: False,
        "_inject_declared_identity": lambda name, args: None,
    }
    exec(compile(body, "<legacy-branch>", "exec"), namespace)   # noqa: S102
    inject = namespace["_inject_user_scope"]

    out = {}
    for name in sorted(_declared_by_every_tool(include_empty=True)):
        args = {}
        inject(name, args)
        if args:
            out[name] = tuple(sorted(args))
    return out


# Generated by measurement against the legacy branch - never edit by hand.
NEWLY_IDENTIFIED = {
    # Added 2026-07-31 in cloud step A. In the workflow lane a step now reaches the
    # WORKFLOW OWNER's connected cloud accounts instead of the machine owner's - the
    # tool used to resolve its caller from an env var nobody sets, so every lane
    # concluded it was the owner and used the owner's stored OAuth credentials.
    "cloud_storage": ('user_role', 'user_scope_id', 'username'),
    # Both added 2026-07-31 with their file_access declaration. In the workflow lane a
    # step now searches / lints inside the workflow owner's tree instead of wherever
    # the path pointed - codesearch previously returned file CONTENT from any absolute
    # path when constructed without a base_dir, which is how the main agent has it.
    "codesearch": ('user_role', 'user_scope_id'),
    # Added with the per-user trust store: this tool reads its own trust policy
    # (vaf/tools/python_exec.py) and without the declaration it read the local
    # ADMIN's bucket for every caller, so one machine-wide "always" answered for
    # everyone. In the workflow lane the step now reads the workflow owner's
    # policy, which is the point.
    "python_exec": ('user_scope_id',),
    # Joined 2026-08-01 (Phase 3): the coder declared nothing, so a workflow step calling
    # it spawned a child that ran every inner tool as the machine owner. The identity now
    # crosses the process boundary as data (VAF_USER_SCOPE_ID/VAF_USER_ROLE).
    "coding_agent": ('user_role', 'user_scope_id'),
    "linter": ('user_role', 'user_scope_id'),
    # Added 2026-07-31 as the first consumer of the `file_access` declaration: it is a
    # WRITE tool whose gap was closed by declaring the mode, and the declaration cannot
    # be made without the identity that resolves it. In workflows this means the step
    # now writes into the workflow owner's tree instead of wherever the name pointed.
    "document_writer": ('user_role', 'user_scope_id'),
    "analyze_image": ('user_scope_id',),
    "browser_agent": ('user_scope_id',),
    "create_automation": ('user_role', 'user_scope_id'),
    "create_skill": ('user_scope_id', 'username'),
    "delete_automation": ('user_role', 'user_scope_id'),
    "delete_skill": ('user_scope_id', 'username'),
    "discord_inbox": ('user_scope_id', 'username'),
    "document_editor": ('user_scope_id',),
    # +user_role 2026-07-31 (file_access declaration). In the workflow lane this
    # means a second admin running these two as a step is no longer jailed - the
    # same direction the other file gates already took.
    "document_viewer": ('user_role', 'user_scope_id'),
    "edit_file": ('user_role', 'user_scope_id'),
    "find_discord_messages": ('user_scope_id', 'username'),
    "find_files": ('user_role', 'user_scope_id'),
    "find_telegram_messages": ('user_scope_id', 'username'),
    "folder_size": ('user_role', 'user_scope_id'),
    "github_create_issue": ('user_scope_id', 'username'),
    "github_get_file": ('user_scope_id', 'username'),
    "github_get_file_structure": ('user_scope_id', 'username'),
    "github_get_tree": ('user_scope_id', 'username'),
    "github_list_directory": ('user_scope_id', 'username'),
    "github_list_issues": ('user_scope_id', 'username'),
    "github_list_pulls": ('user_scope_id', 'username'),
    "github_list_repos": ('user_scope_id', 'username'),
    "github_search_files": ('user_scope_id', 'username'),
    "github_update_file": ('user_scope_id', 'username'),
    "learn_attached_knowledge": ('user_scope_id',),
    "learn_document": ('user_role', 'user_scope_id'),
    "librarian_agent": ('user_role', 'user_scope_id'),
    "list_automations": ('user_role', 'user_scope_id'),
    "list_files": ('user_role', 'user_scope_id'),
    "list_skills": ('user_scope_id', 'username'),
    "list_trash": ('user_role', 'user_scope_id'),
    "read_automation": ('user_role', 'user_scope_id'),
    "read_discord_chat": ('user_scope_id', 'username'),
    "read_file": ('user_role', 'user_scope_id'),
    "read_telegram_chat": ('user_scope_id', 'username'),
    "replace_editor_selection": ('user_scope_id',),
    "restore_automation": ('user_role', 'user_scope_id'),
    "telegram_inbox": ('user_scope_id', 'username'),
    # Added 2026-08-04. Its schema always told the model this field was "injected by the
    # framework"; it was not, because the tool declared no identity_kwargs, so the tool fell
    # back to a PROCESS-GLOBAL environment variable that a background thinking run sets for
    # its whole duration. Registered on every agent, so a tenant's chat turn wrote its note
    # into whichever scope that run was serving - and the note is read back into the OTHER
    # tenant's next thinking prompt, under a header telling the model to follow it carefully.
    "thinking_note_add": ('user_scope_id',),
    "thinking_workspace_handoff": ('user_scope_id',),
    "thinking_workspace_read": ('user_scope_id',),
    "thinking_workspace_write": ('user_scope_id',),
    "tree": ('user_role', 'user_scope_id'),
    "update_automation": ('user_role', 'user_scope_id'),
    "update_intent": ('user_scope_id',),
    "update_skill": ('user_scope_id', 'username'),
    "web_search": ('user_scope_id',),
    "update_working_memory": ('user_scope_id',),
    "write_file": ('user_role', 'user_scope_id'),
}

def test_no_tool_loses_an_identity_key():
    """THE safety property. Widening who receives an identity must never narrow it for
    someone: a tool that stopped receiving its scope would resume writing into the machine
    owner's data, which is the very bug this switch exists to fix."""
    legacy = _legacy_distribution()
    declared = _declared_by_every_tool()
    lost = {name: sorted(set(keys) - set(declared.get(name, ())))
            for name, keys in legacy.items()
            if set(keys) - set(declared.get(name, ()))}
    assert lost == {}, (
        "switching to declared identity would take keys away from these tools; add the "
        "missing key to each tool's identity_kwargs: " + repr(lost)
    )


def test_the_tools_that_gain_an_identity_are_the_ones_recorded():
    """The blast radius. A tool joining this set gains a scope, a role or an owner in every
    workflow step that calls it - that is a security-relevant change and belongs in a diff."""
    legacy = _legacy_distribution()
    declared = _declared_by_every_tool()
    gained = {name: keys for name, keys in declared.items() if name not in legacy}
    added = sorted(set(gained) - set(NEWLY_IDENTIFIED))
    removed = sorted(set(NEWLY_IDENTIFIED) - set(gained))
    assert not added, (
        "these tools now receive an identity in workflows and did not before. That is "
        "usually correct - it is what declaring identity_kwargs means - but it must be a "
        "deliberate line in a diff, so add them here: " + repr(added)
    )
    assert not removed, (
        "these tools stopped gaining an identity. Either they joined the legacy name list "
        "(fine, remove them here) or they lost their declaration (not fine): " + repr(removed)
    )
    differing = {n: (NEWLY_IDENTIFIED[n], gained[n]) for n in gained
                 if n in NEWLY_IDENTIFIED and tuple(gained[n]) != tuple(NEWLY_IDENTIFIED[n])}
    assert not differing, "the keys these tools gain changed: " + repr(differing)


def test_the_switch_reaches_the_file_tools():
    """Named separately because it is the half with teeth: without a scope AND a role the
    per-user file jail cannot form, so before this switch a workflow step could write
    anywhere the machine owner could."""
    for tool in ("read_file", "write_file", "edit_file", "list_files", "tree"):
        assert NEWLY_IDENTIFIED.get(tool) == ("user_role", "user_scope_id"), (
            tool + " no longer gains both halves of the jail identity in workflows"
        )


def test_the_switch_reaches_the_github_tools():
    """The cross-user credential half: token resolution keys on the username, so every
    workflow used to reach for the ADMIN's token whoever started it."""
    github = [n for n in NEWLY_IDENTIFIED if n.startswith("github_")]
    assert len(github) >= 10
    for tool in github:
        assert "username" in NEWLY_IDENTIFIED[tool], tool + " would still resolve a token as admin"
