# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""Frozen record of what the voice-call WebSocket branch SENDS and WRITES, per outcome.

The voice turn pipeline is about to move out of the ~1100-line branch in
vaf/core/web_server.py into a core engine object. That is a large move of code with
side effects, and "nothing changed" is worthless as a claim - this file is the
measurement it has to survive (the same method as tests/test_dispatch_*_baseline.py,
taken for the same reason: a refactor of this size cannot be reviewed by reading it).

HOW IT WAS BUILT - generated by measurement against the UNCHANGED handler, never
typed. The driver walks through websocket_endpoint's real front door (real JWT auth
against a patched secret, the real manager.connect, the real receive loop) with a
fake websocket that scripts receive_text and records send_json. Only model/IO seams
are faked, and they are patched AT THEIR SOURCE MODULES (vaf.core.speech_client,
vaf.core.voice_agent, ...) - never as web_server attributes - so the very same
patches bite after the extraction and the driver survives it unchanged. The cheap
deterministic text heuristics (should_engage, wants_*, addressed_by_name, is_question,
resolve_label, strip_speaker_label, active_speech_seconds on a real WAV fixture) run
REAL, because the routing THROUGH them is the behavior under measurement.

WHAT IS FROZEN: for each scenario, the sequence of voice_* payload SHAPES (type,
key set, variant flags, audio presence - never wording), the record deltas on
_VOICE_CALLS (history length and per-entry truncation prefix, pending_q /
pending_speaker_check / chime_recent / engage_guests / last_self_ts), and the
external calls (TaskQueue.add, speaker_confirm.maybe_request_confirmation).

REGENERATED once, deliberately (2026-08-13): the history-cap normalization
(one 800-char cap in _history_add instead of the grown 200/400/uncapped mix) is a
real behavior change, so the literal was re-measured against the CURRENT handler -
from that change on, this baseline freezes the normalized contract.

DELIBERATELY NOT MEASURED, so the list does not read as complete: greeting audio
bytes; real STT/LLM/ONNX behavior (tests/test_voice_agent.py owns that); the
interleaving of state writes vs TTS within one turn (unobservable through the
sequential per-socket loop); wall-clock timing values (only the KEY SET of `timings`
is frozen); the chunk/reset endpointer lane; multi-socket concurrency.
"""
from __future__ import annotations

import asyncio
import io
import json
import struct
import wave
from typing import Any, Dict, List, Optional

import pytest


# ── audio fixtures: tiny real WAVs (active_speech_seconds runs REAL) ──────────

def _wav(seconds: float, loud: bool) -> bytes:
    buf = io.BytesIO()
    with wave.open(buf, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(16000)
        n = int(16000 * seconds)
        amp = 12000 if loud else 10
        frames = b"".join(
            struct.pack("<h", amp if (i // 40) % 2 == 0 else -amp) for i in range(n))
        w.writeframes(frames)
    return buf.getvalue()


import base64 as _b64

SPEECH_WAV = _b64.b64encode(_wav(1.2, loud=True)).decode()
NOISE_WAV = _b64.b64encode(_wav(0.15, loud=True)).decode()   # < 0.3 s active speech

SCOPE = "deadbeef-0000-0000-0000-000000000000"


# ── the fake websocket ────────────────────────────────────────────────────────

class FakeWebSocket:
    def __init__(self, frames: List[dict], on_drained=None):
        from fastapi import WebSocketDisconnect
        self._frames = [json.dumps(f) for f in frames]
        self._disconnect = WebSocketDisconnect
        self._on_drained = on_drained   # snapshot hook: runs BEFORE the teardown pop
        self.sent: List[dict] = []
        self.cookies: Dict[str, str] = {}
        self.headers: Dict[str, str] = {}
        self.client = type("C", (), {"host": "127.0.0.1", "port": 1234})()

    async def accept(self):
        return None

    async def close(self, code: int = 1000, reason: str = ""):
        raise AssertionError(f"handshake rejected: {code} {reason}")

    async def receive_text(self) -> str:
        if self._frames:
            return self._frames.pop(0)
        # The registry entry is popped by the disconnect teardown (web_server
        # WebSocketDisconnect handler), so the record snapshot must be taken NOW -
        # after the last scripted frame was fully processed, before the teardown.
        if self._on_drained:
            self._on_drained()
        raise self._disconnect(code=1000)

    async def send_json(self, payload: dict):
        self.sent.append(payload)

    async def send_text(self, payload: str):
        self.sent.append(json.loads(payload))


# ── the driver ───────────────────────────────────────────────────────────────

@pytest.fixture
def voice_env(monkeypatch, tmp_path):
    """Everything the handler consults, pinned - the context is part of the
    measurement (house lesson: an unpinned Config once made a baseline a fact
    about one laptop instead of about the code)."""
    import vaf.core.web_server as ws
    import vaf.auth.crypto as crypto
    import vaf.core.speech_client as speech_client
    import vaf.core.voice_agent as va
    import vaf.core.voice_policy as vp
    import vaf.core.speaker_id as sid
    import vaf.core.speaker_confirm as sconf
    import vaf.core.subagent_ipc as ipc
    import vaf.core.voice_vad as vvad
    from vaf.core.config import Config
    from vaf.core.task_queue import TaskQueue

    env: Dict[str, Any] = {"tq_calls": [], "confirm_calls": [], "cfg": {}}

    # -- auth: a REAL jwt against a pinned secret; the handler decodes it itself.
    monkeypatch.setattr(crypto, "get_jwt_secret", lambda: "test-secret")
    import jwt as _jwt
    env["token"] = _jwt.encode(
        {"sub": "u1", "user_scope_id": SCOPE, "username": "tenant", "role": "admin",
         "session_id": None},
        "test-secret", algorithm="HS256")
    monkeypatch.setattr(ws, "_ws_client_ip", lambda w: "127.0.0.1")

    # -- config, pinned (fallthrough to the real default for everything unnamed).
    _cfg = {"local_network_enabled": False, "default_language": "de",
            "speaker_id_enabled": True, "voice_awareness_topics": [],
            "voice_awareness_activity": 0.5,
            "voice_semantic_endpoint_enabled": False}
    env["cfg"] = _cfg
    real_get = Config.get

    def cfg_get(key, default=None):
        if key in _cfg:
            return _cfg[key]
        return real_get(key, default)

    monkeypatch.setattr(Config, "get", staticmethod(cfg_get))

    # -- the manager: patch ON THE INSTANCE (singleton monkeypatch trap).
    monkeypatch.setattr(ws.manager, "get_connection_user", lambda w: SCOPE)
    monkeypatch.setattr(ws.manager, "get_connection_username", lambda w: "tenant")

    # -- pre-loop noise kept cheap and offline.
    monkeypatch.setattr(ws.session_mgr, "list_ui",
                        lambda **kw: [], raising=False)

    # -- model/IO seams, at their SOURCE modules.
    monkeypatch.setattr(va, "available", lambda: True)
    monkeypatch.setattr(va, "is_exclusive", lambda: env.get("exclusive", False))
    monkeypatch.setattr(va, "dedicated_local_model", lambda: None)
    # Long AND token-varied: looks_garbled runs REAL and flags repetition as STT
    # noise (unique tokens must exceed half the total) - a repeated phrase pushed
    # three scenarios into the garble-silent path and the baseline froze the wrong
    # outcome for them (measurement bug #3 of this file).
    _long_stt = ("also ich wollte nochmal ausfuehrlich erzaehlen was diese woche "
                 "alles passiert ist zuerst hatten wir montag das lange gespraech "
                 "mit dem architekten ueber den umbau dann kam dienstag die "
                 "lieferung der neuen kuechengeraete leider fehlte ein teil "
                 "weshalb mittwoch jemand vom kundendienst vorbeikommen musste "
                 "donnerstag habe ich endlich den vertrag unterschrieben und "
                 "freitag sind wir abends noch essen gegangen um alles zu feiern "
                 "samstag war dann grosser hausputz angesagt weil sonntag "
                 "ueberraschend besuch aus muenchen angekommen ist")
    monkeypatch.setattr(speech_client, "transcribe",
                        lambda *a, **kw: (env.get("stt_text", _long_stt),
                                          env.get("stt_lang", "de")))
    monkeypatch.setattr(sid, "is_enabled", lambda: env.get("speaker_enabled", False))
    monkeypatch.setattr(sid, "load_profile", lambda scope: env.get("profile"))
    monkeypatch.setattr(sid, "prewarm", lambda *a, **kw: None)
    monkeypatch.setattr(sid, "score_wav",
                        lambda *a, **kw: env.get("score", {"score": 0.9, "label": "self",
                                                           "name": None}))
    monkeypatch.setattr(sconf, "maybe_request_confirmation",
                        lambda **kw: env["confirm_calls"].append(kw))
    _long_reply = ("das ist eine ausfuehrliche antwort mit vielen einzelheiten "
                   "zur geplanten woche ") * 6   # ~480 chars: uncapped-path visible
    monkeypatch.setattr(va, "voice_reply",
                        lambda *a, **kw: env.get("reply", {"reply": _long_reply,
                                                           "delegate": None,
                                                           "silent": False}))
    monkeypatch.setattr(va, "chime_in_reply", lambda *a, **kw: env.get("chime", ""))
    monkeypatch.setattr(vp, "chime_decision",
                        lambda *a, **kw: env.get("chime_decision",
                                                 {"speak": False, "mode": "quiet",
                                                  "scene": "multi", "score": 0.0,
                                                  "interesting": False, "trigger": None}))
    monkeypatch.setattr(vp, "answer_verdict",
                        lambda *a, **kw: env.get("answer",
                                                 {"verdict": "continue",
                                                  "reason": "non_owner", "guest": False}))
    monkeypatch.setattr(vp, "similar_to_any", lambda *a, **kw: False)
    monkeypatch.setattr(vvad, "get_turn_judge", lambda: None)

    class _FakeIpc:
        def get_active_tasks(self):
            return env.get("subagents", [])

    monkeypatch.setattr(ipc, "get_ipc", lambda: _FakeIpc())

    def rec_add(self, session_id=None, input_text=None, **kw):
        env["tq_calls"].append({"session_id": session_id,
                                "input_text": input_text, **kw})
        return "task-1"

    monkeypatch.setattr(TaskQueue, "add", rec_add)

    # -- TTS: SpeechManager instance with deterministic bytes.
    class _FakeSM:
        def synthesize_audio(self, text, lang, **kw):
            return b"AUDIO"

        def call_lane_speaks(self, lang):
            return True

    from vaf.core.speech import SpeechManager
    monkeypatch.setattr(SpeechManager, "get_instance", classmethod(lambda cls: _FakeSM()))

    env["ws_mod"] = ws
    return env


def _drive(env, frames: List[dict]) -> FakeWebSocket:
    ws_mod = env["ws_mod"]

    def snap():
        env["record_snapshot"] = _snapshot_record(ws_mod)

    sock = FakeWebSocket(frames, on_drained=snap)
    asyncio.run(ws_mod.websocket_endpoint(sock, token=env["token"]))
    return sock


def _snapshot_record(ws_mod) -> Optional[dict]:
    regs = ws_mod._VOICE_CALLS
    if not regs:
        return None
    rec = list(regs.values())[0]
    return {
        # Length is pinned only where truncation can bite (>= 100 chars): the short
        # vocab-picked lines (greeting, clarify, reask) vary in length per pick -
        # freezing their exact length froze the dice, found when the recheck
        # scenario diverged between two runs of the SAME code (measurement bug #1
        # of this baseline, same class as the five the dispatch baselines caught).
        "history": [(h["role"], len(h["content"]) if len(h["content"]) >= 100
                     else "short") for h in rec.get("history", [])],
        "pending_q": bool(rec.get("pending_q")),
        "pending_speaker_check": bool(rec.get("pending_speaker_check")),
        "chime_recent": len(rec.get("chime_recent", [])),
        "engage_guests": bool(rec.get("engage_guests")),
        "last_self_ts": rec.get("last_self_ts") is not None,
    }


def _voice_sends(sock: FakeWebSocket) -> List[dict]:
    return [p for p in sock.sent
            if str(p.get("type", "")).startswith(("voice_", "speaker_enroll_tts"))]


def _shape(p: dict) -> tuple:
    """A payload's SHAPE: type, sorted keys, the variant flags that are True,
    audio presence - never wording."""
    flags = tuple(sorted(k for k in ("clarify", "reask", "chime_in", "silent",
                                     "greeting") if p.get(k)))
    return (p.get("type"), tuple(sorted(p.keys())), flags,
            p.get("error"), ("audio" in p and p.get("audio") is not None))


def _record(env) -> Optional[dict]:
    return env.get("record_snapshot")


START = {"type": "voice_call_start", "ui_lang": "de"}


def _turn(audio=SPEECH_WAV, **over) -> dict:
    d = {"type": "voice_call_turn", "audio": audio, "format": "wav",
         "sessionId": "", "main_busy": False, "pending_task": ""}
    d.update(over)
    return d


# ═════════════════════════════════════════════════════════════════════════════
# VOICE_BASELINE - generated by measurement against the unchanged handler
# (2026-08-12); never edit by hand. Regenerate with the same driver if a
# DELIBERATE behavior change is made, and say so in the commit.
# ═════════════════════════════════════════════════════════════════════════════
VOICE_BASELINE = {'addressee_clarify': {'confirms': 0,
                       'record': {'chime_recent': 0,
                                  'engage_guests': False,
                                  'history': [('assistant', 'short'),
                                              ('user', 'short'),
                                              ('assistant', 'short')],
                                  'last_self_ts': False,
                                  'pending_q': False,
                                  'pending_speaker_check': False},
                       'sends': [('voice_call_started',
                                  ('exclusive',
                                   'lang',
                                   'ok',
                                   'reason',
                                   'server_endpoint',
                                   'type'),
                                  (),
                                  None,
                                  False),
                                 ('voice_call_reply',
                                  ('audio',
                                   'delegated',
                                   'greeting',
                                   'reply',
                                   'speaker_label',
                                   'type',
                                   'user_text'),
                                  ('greeting',),
                                  None,
                                  True),
                                 ('voice_call_reply',
                                  ('audio',
                                   'clarify',
                                   'delegated',
                                   'reply',
                                   'speaker_label',
                                   'type',
                                   'user_text'),
                                  ('clarify',),
                                  None,
                                  True)],
                       'tq': []},
 'bad_format': {'confirms': 0,
                'record': {'chime_recent': 0,
                           'engage_guests': False,
                           'history': [('assistant', 'short')],
                           'last_self_ts': False,
                           'pending_q': False,
                           'pending_speaker_check': False},
                'sends': [('voice_call_started',
                           ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                           (),
                           None,
                           False),
                          ('voice_call_reply',
                           ('audio',
                            'delegated',
                            'greeting',
                            'reply',
                            'speaker_label',
                            'type',
                            'user_text'),
                           ('greeting',),
                           None,
                           True),
                          ('voice_call_error', ('error', 'type'), (), 'bad_format', False)],
                'tq': []},
 'busy_local_flag': {'confirms': 0,
                     'record': {'chime_recent': 0,
                                'engage_guests': False,
                                'history': [('assistant', 'short')],
                                'last_self_ts': False,
                                'pending_q': False,
                                'pending_speaker_check': False},
                     'sends': [('voice_call_started',
                                ('exclusive',
                                 'lang',
                                 'ok',
                                 'reason',
                                 'server_endpoint',
                                 'type'),
                                (),
                                None,
                                False),
                               ('voice_call_reply',
                                ('audio',
                                 'delegated',
                                 'greeting',
                                 'reply',
                                 'speaker_label',
                                 'type',
                                 'user_text'),
                                ('greeting',),
                                None,
                                True),
                               ('voice_call_error',
                                ('error', 'type'),
                                (),
                                'busy_local',
                                False)],
                     'tq': []},
 'busy_local_subagent': {'confirms': 0,
                         'record': {'chime_recent': 0,
                                    'engage_guests': False,
                                    'history': [('assistant', 'short')],
                                    'last_self_ts': False,
                                    'pending_q': False,
                                    'pending_speaker_check': False},
                         'sends': [('voice_call_started',
                                    ('exclusive',
                                     'lang',
                                     'ok',
                                     'reason',
                                     'server_endpoint',
                                     'type'),
                                    (),
                                    None,
                                    False),
                                   ('voice_call_reply',
                                    ('audio',
                                     'delegated',
                                     'greeting',
                                     'reply',
                                     'speaker_label',
                                     'type',
                                     'user_text'),
                                    ('greeting',),
                                    None,
                                    True),
                                   ('voice_call_error',
                                    ('error', 'type'),
                                    (),
                                    'busy_local',
                                    False)],
                         'tq': []},
 'chime_in': {'confirms': 0,
              'record': {'chime_recent': 1,
                         'engage_guests': False,
                         'history': [('assistant', 'short'),
                                     ('user', 'short'),
                                     ('assistant', 'short')],
                         'last_self_ts': False,
                         'pending_q': False,
                         'pending_speaker_check': False},
              'sends': [('voice_call_started',
                         ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                         (),
                         None,
                         False),
                        ('voice_call_reply',
                         ('audio',
                          'delegated',
                          'greeting',
                          'reply',
                          'speaker_label',
                          'type',
                          'user_text'),
                         ('greeting',),
                         None,
                         True),
                        ('voice_call_reply',
                         ('audio',
                          'chime_in',
                          'delegated',
                          'reply',
                          'speaker_label',
                          'type',
                          'user_text'),
                         ('chime_in',),
                         None,
                         True)],
              'tq': []},
 'delegation': {'confirms': 0,
                'record': {'chime_recent': 0,
                           'engage_guests': False,
                           'history': [('assistant', 'short'),
                                       ('user', 530),
                                       ('assistant', 'short')],
                           'last_self_ts': False,
                           'pending_q': False,
                           'pending_speaker_check': False},
                'sends': [('voice_call_started',
                           ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                           (),
                           None,
                           False),
                          ('voice_call_reply',
                           ('audio',
                            'delegated',
                            'greeting',
                            'reply',
                            'speaker_label',
                            'type',
                            'user_text'),
                           ('greeting',),
                           None,
                           True),
                          ('voice_call_reply',
                           ('audio',
                            'delegated',
                            'reply',
                            'speaker_label',
                            'timings',
                            'type',
                            'user_text'),
                           (),
                           None,
                           True)],
                'tq': [{'metadata_keys': ('origin_channel', 'user_scope_id'),
                        'session_id': ''}]},
 'guest_side_talk_silent': {'confirms': 0,
                            'record': {'chime_recent': 0,
                                       'engage_guests': False,
                                       'history': [('assistant', 'short'), ('user', 'short')],
                                       'last_self_ts': False,
                                       'pending_q': False,
                                       'pending_speaker_check': False},
                            'sends': [('voice_call_started',
                                       ('exclusive',
                                        'lang',
                                        'ok',
                                        'reason',
                                        'server_endpoint',
                                        'type'),
                                       (),
                                       None,
                                       False),
                                      ('voice_call_reply',
                                       ('audio',
                                        'delegated',
                                        'greeting',
                                        'reply',
                                        'speaker_label',
                                        'type',
                                        'user_text'),
                                       ('greeting',),
                                       None,
                                       True),
                                      ('voice_call_reply',
                                       ('audio',
                                        'delegated',
                                        'reply',
                                        'silent',
                                        'speaker_label',
                                        'type',
                                        'user_text'),
                                       ('silent',),
                                       None,
                                       False)],
                            'tq': []},
 'llm_failed': {'confirms': 0,
                'record': {'chime_recent': 0,
                           'engage_guests': False,
                           'history': [('assistant', 'short')],
                           'last_self_ts': False,
                           'pending_q': False,
                           'pending_speaker_check': False},
                'sends': [('voice_call_started',
                           ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                           (),
                           None,
                           False),
                          ('voice_call_reply',
                           ('audio',
                            'delegated',
                            'greeting',
                            'reply',
                            'speaker_label',
                            'type',
                            'user_text'),
                           ('greeting',),
                           None,
                           True),
                          ('voice_call_error', ('error', 'type'), (), 'llm_failed', False)],
                'tq': []},
 'model_silence': {'confirms': 0,
                   'record': {'chime_recent': 0,
                              'engage_guests': False,
                              'history': [('assistant', 'short'), ('user', 530)],
                              'last_self_ts': False,
                              'pending_q': False,
                              'pending_speaker_check': False},
                   'sends': [('voice_call_started',
                              ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                              (),
                              None,
                              False),
                             ('voice_call_reply',
                              ('audio',
                               'delegated',
                               'greeting',
                               'reply',
                               'speaker_label',
                               'type',
                               'user_text'),
                              ('greeting',),
                              None,
                              True),
                             ('voice_call_reply',
                              ('audio',
                               'delegated',
                               'reply',
                               'silent',
                               'speaker_label',
                               'type',
                               'user_text'),
                              ('silent',),
                              None,
                              False)],
                   'tq': []},
 'noise_gated': {'confirms': 0,
                 'record': {'chime_recent': 0,
                            'engage_guests': False,
                            'history': [('assistant', 'short')],
                            'last_self_ts': False,
                            'pending_q': False,
                            'pending_speaker_check': False},
                 'sends': [('voice_call_started',
                            ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                            (),
                            None,
                            False),
                           ('voice_call_reply',
                            ('audio',
                             'delegated',
                             'greeting',
                             'reply',
                             'speaker_label',
                             'type',
                             'user_text'),
                            ('greeting',),
                            None,
                            True),
                           ('voice_call_error', ('error', 'type'), (), 'no_speech', False)],
                 'tq': []},
 'normal_reply': {'confirms': 0,
                  'record': {'chime_recent': 0,
                             'engage_guests': False,
                             'history': [('assistant', 'short'),
                                         ('user', 530),
                                         ('assistant', 474)],
                             'last_self_ts': False,
                             'pending_q': False,
                             'pending_speaker_check': False},
                  'sends': [('voice_call_started',
                             ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                             (),
                             None,
                             False),
                            ('voice_call_reply',
                             ('audio',
                              'delegated',
                              'greeting',
                              'reply',
                              'speaker_label',
                              'type',
                              'user_text'),
                             ('greeting',),
                             None,
                             True),
                            ('voice_call_reply',
                             ('audio',
                              'delegated',
                              'reply',
                              'speaker_label',
                              'timings',
                              'type',
                              'user_text'),
                             (),
                             None,
                             True)],
                  'tq': []},
 'recheck_unsure_directed': {'confirms': 0,
                             'record': {'chime_recent': 0,
                                        'engage_guests': False,
                                        'history': [('assistant', 'short'),
                                                    ('user', 'short'),
                                                    ('assistant', 'short')],
                                        'last_self_ts': False,
                                        'pending_q': False,
                                        'pending_speaker_check': True},
                             'sends': [('voice_call_started',
                                        ('exclusive',
                                         'lang',
                                         'ok',
                                         'reason',
                                         'server_endpoint',
                                         'type'),
                                        (),
                                        None,
                                        False),
                                       ('voice_call_reply',
                                        ('audio',
                                         'delegated',
                                         'greeting',
                                         'reply',
                                         'speaker_label',
                                         'type',
                                         'user_text'),
                                        ('greeting',),
                                        None,
                                        True),
                                       ('voice_call_reply',
                                        ('audio',
                                         'clarify',
                                         'delegated',
                                         'reply',
                                         'speaker_label',
                                         'type',
                                         'user_text'),
                                        ('clarify',),
                                        None,
                                        True)],
                             'tq': []},
 'second_start_resets': {'confirms': 0,
                         'record': {'chime_recent': 0,
                                    'engage_guests': False,
                                    'history': [('assistant', 'short')],
                                    'last_self_ts': False,
                                    'pending_q': False,
                                    'pending_speaker_check': False},
                         'sends': [('voice_call_started',
                                    ('exclusive',
                                     'lang',
                                     'ok',
                                     'reason',
                                     'server_endpoint',
                                     'type'),
                                    (),
                                    None,
                                    False),
                                   ('voice_call_reply',
                                    ('audio',
                                     'delegated',
                                     'greeting',
                                     'reply',
                                     'speaker_label',
                                     'type',
                                     'user_text'),
                                    ('greeting',),
                                    None,
                                    True),
                                   ('voice_call_reply',
                                    ('audio',
                                     'delegated',
                                     'reply',
                                     'speaker_label',
                                     'timings',
                                     'type',
                                     'user_text'),
                                    (),
                                    None,
                                    True),
                                   ('voice_call_started',
                                    ('exclusive',
                                     'lang',
                                     'ok',
                                     'reason',
                                     'server_endpoint',
                                     'type'),
                                    (),
                                    None,
                                    False),
                                   ('voice_call_reply',
                                    ('audio',
                                     'delegated',
                                     'greeting',
                                     'reply',
                                     'speaker_label',
                                     'type',
                                     'user_text'),
                                    ('greeting',),
                                    None,
                                    True)],
                         'tq': []},
 'stt_empty': {'confirms': 0,
               'record': {'chime_recent': 0,
                          'engage_guests': False,
                          'history': [('assistant', 'short')],
                          'last_self_ts': False,
                          'pending_q': False,
                          'pending_speaker_check': False},
               'sends': [('voice_call_started',
                          ('exclusive', 'lang', 'ok', 'reason', 'server_endpoint', 'type'),
                          (),
                          None,
                          False),
                         ('voice_call_reply',
                          ('audio',
                           'delegated',
                           'greeting',
                           'reply',
                           'speaker_label',
                           'type',
                           'user_text'),
                          ('greeting',),
                          None,
                          True),
                         ('voice_call_error', ('error', 'type'), (), 'no_speech', False)],
               'tq': []}}



def _scenario(env, name):
    """Configure env per scenario; returns the frame script."""
    if name == "normal_reply":
        return [START, _turn()]
    if name == "bad_format":
        return [START, {"type": "voice_call_turn", "audio": "", "format": "wav",
                        "sessionId": ""}]
    if name == "noise_gated":
        return [START, _turn(audio=NOISE_WAV)]
    if name == "stt_empty":
        env["stt_text"] = ""
        return [START, _turn()]
    if name == "busy_local_flag":
        env["exclusive"] = True
        return [START, _turn(main_busy=True)]
    if name == "busy_local_subagent":
        env["exclusive"] = True
        env["subagents"] = [{"task_id": "t1"}]
        return [START, _turn()]
    if name == "llm_failed":
        env["reply"] = None
        return [START, _turn()]
    if name == "model_silence":
        env["reply"] = {"reply": "<silent/>", "delegate": None, "silent": True}
        return [START, _turn()]
    if name == "delegation":
        env["reply"] = {"reply": "Mach ich!", "delegate": "wetter pruefen",
                        "silent": False}
        return [START, _turn(sessionId="")]
    if name == "guest_side_talk_silent":
        env["speaker_enabled"] = True
        env["profile"] = {"name": "Alice"}
        env["score"] = {"score": 0.2, "label": "other", "name": None}
        env["stt_text"] = "wir gehen dann gleich einkaufen ja"
        return [START, _turn()]
    if name == "chime_in":
        env["speaker_enabled"] = True
        env["profile"] = {"name": "Alice"}
        env["score"] = {"score": 0.2, "label": "other", "name": None}
        env["stt_text"] = "wir gehen dann gleich einkaufen ja"
        env["chime_decision"] = {"speak": True, "mode": "quiet", "scene": "multi",
                                 "score": 0.9, "interesting": True, "trigger": None}
        env["chime"] = "Interessant!"
        return [START, _turn()]
    if name == "addressee_clarify":
        env["speaker_enabled"] = True
        env["profile"] = {"name": "Alice"}
        env["score"] = {"score": 0.2, "label": "other", "name": None}
        env["stt_text"] = "kannst du mich hoeren"
        return [START, _turn()]
    if name == "recheck_unsure_directed":
        env["speaker_enabled"] = True
        env["profile"] = {"name": "Alice"}
        env["score"] = {"score": 0.5, "label": "unsure", "name": None}
        env["stt_text"] = "kannst du bitte antworten"
        return [START, _turn()]
    if name == "second_start_resets":
        return [START, _turn(), START]
    raise KeyError(name)


SCENARIOS = ["normal_reply", "bad_format", "noise_gated", "stt_empty",
             "busy_local_flag", "busy_local_subagent", "llm_failed",
             "model_silence", "delegation", "guest_side_talk_silent",
             "chime_in", "addressee_clarify", "recheck_unsure_directed",
             "second_start_resets"]


def _measure(env, name) -> dict:
    env["ws_mod"]._VOICE_CALLS.clear()
    frames = _scenario(env, name)
    sock = _drive(env, frames)
    return {
        "sends": [_shape(p) for p in _voice_sends(sock)],
        "record": _record(env),
        "tq": [{"session_id": c["session_id"],
                "metadata_keys": tuple(sorted((c.get("metadata") or {}).keys()))}
               for c in env["tq_calls"]],
        "confirms": len(env["confirm_calls"]),
    }


@pytest.mark.parametrize("name", SCENARIOS)
def test_the_voice_branch_matches_its_baseline(voice_env, name):
    measured = _measure(voice_env, name)
    assert measured == VOICE_BASELINE[name], (
        f"scenario {name!r} diverged from the frozen measurement - either the "
        f"extraction changed behavior (fix it) or a deliberate change needs a "
        f"REGENERATED baseline with the reason in the commit message"
    )
