# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""Frozen record of every kwarg the dispatcher hands each tool, measured before the split.

`Agent.execute_tool` is about to be cut in two: the pipeline (policy, gate, repair, identity,
bounded execution, events) moves to a caller-agnostic funnel so the workflow engine, the
librarian and the coder stop reimplementing it, while the chat-turn machinery (the four
gates, the sub-agent prewrite, the python_exec fallback) stays behind in the agent. That is a
large move of code with side effects, and "nothing changed" is worthless as a claim. This is
the measurement it has to survive.

WHAT IS PINNED. Per tool, the exact set of keys the dispatcher ADDS to the model's arguments -
identity (`user_scope_id`, `username`, `user_role`) and plumbing (`_agent`, `_session_id`,
`session_id`, `_session_workspace`, `_is_channel_session`) alike. Both directions are
failures: one key fewer and a tool silently loses its scope or its bridge to the agent; one
more and a tool starts branching on a value it never had, or writes into the session
workspace instead of where it used to.

HOW IT WAS BUILT. Generated by measurement, never typed. The same list was typed by hand once
during the identity-declaration round and the guard immediately caught nine invented entries
and five missing ones; a hand-written baseline pins the author's belief, not the behaviour.

WHY A FAKE AGENT. Constructing a real `Agent` loads config, resolves a model and builds an
HTTP backend - too slow and too network-dependent for CI. So the guard drives a
`SimpleNamespace`. That is only trustworthy if it answers like the real thing, so the fake was
run against a real `Agent` over all 117 registered tools: 117 measured, 0 differences. When
the fake stops mirroring the dispatcher it will show up here as a diff, not as a silent pass.

THE CONTEXT IS PART OF THE MEASUREMENT. Several branches are conditional, so the numbers only
mean something for one fixed situation: a web (non-channel) chat turn, run kind "chat", an
admin role (so `admin_only` tools reach the injection stage instead of being blocked before
it), no session id, and every tool pre-approved past the confirmation gate. `ask_user` is the
one tool whose identity injection is conditional on the run kind - see
tests/test_identity_kwargs_declaration.py, which pins that separately.
"""
import os
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from conftest import bind_chat_stages
from vaf.core.agent import Agent
from vaf.tools.base import BaseTool

os.environ.setdefault("VAF_NONINTERACTIVE", "1")

SCOPE = "deadbeef-0000-0000-0000-000000000000"   # synthetic; never a real scope UUID


# Generated by measurement against the unchanged dispatcher - never edit by hand.
# tool name -> (context it was measured in, keys the dispatcher ADDS)
KWARGS_BASELINE = {
    "add_automation_note":       ("chat", ["user_scope_id"]),
    "add_automation_todo":       ("chat", ["user_scope_id"]),
    "add_memory":                ("chat", []),
    "add_task":                  ("chat", []),
    "analyze_image":             ("chat", ["_agent", "session_id", "user_scope_id"]),
    "archive_mail":              ("chat", ["user_scope_id", "username"]),
    "ask_user":                  ("chat", ["_agent"]),
    "bash":                      ("chat", []),
    "browser_agent":             ("chat", ["user_scope_id"]),
    "cancel_timer":              ("chat", ["_agent"]),
    "checkpoint_context":        ("chat", ["_agent"]),
    "cloud_storage":             ("chat", []),
    "codesearch":                ("chat", []),
    "coding_agent":              ("chat", []),
    "create_agent_tool":         ("chat", ["_agent"]),
    "create_agent_workflow":     ("chat", ["_agent"]),
    "create_automation":         ("chat", ["user_role", "user_scope_id"]),
    "create_calendar_event":     ("chat", ["user_scope_id", "username"]),
    "create_contact":            ("chat", ["user_scope_id", "username"]),
    "create_skill":              ("chat", ["user_scope_id", "username"]),
    "delete_automation":         ("chat", ["user_role", "user_scope_id"]),
    "delete_automation_note":    ("chat", ["user_scope_id"]),
    "delete_automation_todo":    ("chat", ["user_scope_id"]),
    "delete_calendar_event":     ("chat", ["user_scope_id", "username"]),
    "delete_contact":            ("chat", ["user_scope_id", "username"]),
    "delete_mail":               ("chat", ["user_scope_id", "username"]),
    "delete_skill":              ("chat", ["user_scope_id", "username"]),
    "discord_inbox":             ("chat", ["user_scope_id", "username"]),
    "document_agent":            ("chat", []),
    "document_editor":           ("chat", ["user_scope_id"]),
    "document_viewer":           ("chat", ["user_scope_id"]),
    "document_writer":           ("chat", ["_session_id"]),
    "edit_file":                 ("chat", ["user_role", "user_scope_id"]),
    "execute_workflow":          ("chat", ["_agent"]),
    "find_discord_messages":     ("chat", ["user_scope_id", "username"]),
    "find_files":                ("chat", ["user_role", "user_scope_id"]),
    "find_mail":                 ("chat", ["user_scope_id", "username"]),
    "find_telegram_messages":    ("chat", ["user_scope_id", "username"]),
    "find_whatsapp_messages":    ("chat", ["user_scope_id", "username"]),
    "folder_size":               ("chat", ["user_role", "user_scope_id"]),
    "forward_mail":              ("chat", ["user_scope_id", "username"]),
    "get_contact":               ("chat", ["user_scope_id", "username"]),
    "git_add_commit":            ("chat", []),
    "git_init":                  ("chat", []),
    "git_log":                   ("chat", []),
    "git_status":                ("chat", []),
    "github_create_issue":       ("chat", ["user_scope_id", "username"]),
    "github_get_file":           ("chat", ["user_scope_id", "username"]),
    "github_get_file_structure": ("chat", ["user_scope_id", "username"]),
    "github_get_tree":           ("chat", ["user_scope_id", "username"]),
    "github_list_directory":     ("chat", ["user_scope_id", "username"]),
    "github_list_issues":        ("chat", ["user_scope_id", "username"]),
    "github_list_pulls":         ("chat", ["user_scope_id", "username"]),
    "github_list_repos":         ("chat", ["user_scope_id", "username"]),
    "github_search_files":       ("chat", ["user_scope_id", "username"]),
    "github_update_file":        ("chat", ["user_scope_id", "username"]),
    "host_bash":                 ("chat", ["_is_channel_session"]),
    "label_mail":                ("chat", ["user_scope_id", "username"]),
    "learn_attached_knowledge":  ("chat", ["_agent", "session_id", "user_scope_id"]),
    "learn_document":            ("chat", ["_agent", "user_scope_id"]),
    "librarian_agent":           ("chat", ["user_role", "user_scope_id"]),
    "linter":                    ("chat", []),
    "list_automation_notes":     ("chat", ["user_scope_id"]),
    "list_automation_todos":     ("chat", ["user_scope_id"]),
    "list_automations":          ("chat", ["user_role", "user_scope_id"]),
    "list_calendar_events":      ("chat", ["user_scope_id", "username"]),
    "list_contacts":             ("chat", ["user_scope_id", "username"]),
    "list_email_accounts":       ("chat", ["user_scope_id", "username"]),
    "list_files":                ("chat", ["user_role", "user_scope_id"]),
    "list_skills":               ("chat", ["user_scope_id", "username"]),
    "list_timers":               ("chat", ["_agent"]),
    "list_tools":                ("chat", []),
    "list_trash":                ("chat", ["user_role", "user_scope_id"]),
    "list_workflows":            ("chat", []),
    "mail_inbox":                ("chat", ["user_scope_id", "username"]),
    "mark_mail_answered":        ("chat", ["user_scope_id", "username"]),
    "mcp_call":                  ("chat", []),
    "memory_save":               ("chat", ["user_scope_id"]),
    "memory_search":             ("chat", ["user_scope_id"]),
    "move_file":                 ("chat", []),
    "project_history":           ("chat", []),
    "project_rollback":          ("chat", []),
    "python_exec":               ("chat", ["_agent"]),
    "python_sandbox":            ("chat", ["_agent", "_session_id", "user_scope_id"]),
    "read_automation":           ("chat", ["user_role", "user_scope_id"]),
    "read_discord_chat":         ("chat", ["user_scope_id", "username"]),
    "read_file":                 ("chat", ["user_role", "user_scope_id"]),
    "read_mail":                 ("chat", ["user_scope_id", "username"]),
    "read_skill":                ("chat", ["user_scope_id", "username"]),
    "read_telegram_chat":        ("chat", ["user_scope_id", "username"]),
    "read_whatsapp_chat":        ("chat", ["user_scope_id", "username"]),
    "repair_report":             ("chat", []),
    "replace_editor_selection":  ("chat", ["user_scope_id"]),
    "replace_editor_text":       ("chat", []),
    "reply_mail":                ("chat", ["user_scope_id", "username"]),
    "report_filename":           ("chat", []),
    "request_clarification":     ("chat", []),
    "research_agent":            ("chat", []),
    "restore_automation":        ("chat", ["user_role", "user_scope_id"]),
    "run_tests":                 ("chat", []),
    "save_thinking_suggestion":  ("chat", []),
    "schedule_reminder":         ("chat", ["user_scope_id", "username"]),
    "search_tools":              ("chat", []),
    "send_discord":              ("chat", ["_agent", "user_scope_id", "username"]),
    "send_mail":                 ("chat", ["user_role", "user_scope_id", "username"]),
    "send_slack":                ("chat", ["_agent", "user_scope_id", "username"]),
    "send_telegram":             ("chat", ["_agent", "user_scope_id", "username"]),
    "send_to_user":              ("chat", ["_agent", "user_scope_id", "username"]),
    "send_whatsapp":             ("chat", ["_agent", "user_scope_id", "username"]),
    "set_git_coauthor":          ("chat", []),
    "set_timer":                 ("chat", ["_agent"]),
    "telegram_inbox":            ("chat", ["user_scope_id", "username"]),
    "thinking_done":             ("thinking", []),
    "thinking_note_add":         ("chat", []),
    "thinking_workspace_handoff":("thinking", ["user_scope_id"]),
    "thinking_workspace_read":   ("thinking", ["user_scope_id"]),
    "thinking_workspace_write":  ("thinking", ["user_scope_id"]),
    "tree":                      ("chat", ["user_role", "user_scope_id"]),
    "update_automation":         ("chat", ["user_role", "user_scope_id"]),
    "update_calendar_event":     ("chat", ["user_scope_id", "username"]),
    "update_codex":              ("chat", []),
    "update_contact":            ("chat", ["user_scope_id", "username"]),
    "update_intent":             ("chat", ["user_scope_id"]),
    "update_skill":              ("chat", ["user_scope_id", "username"]),
    "update_user_identity":      ("chat", ["username"]),
    "update_working_memory":     ("chat", ["user_scope_id"]),
    "use_skill":                 ("chat", ["user_scope_id"]),
    "web_search":                ("chat", []),
    "webfetch":                  ("chat", []),
    "whatsapp_call":             ("chat", ["user_scope_id", "username"]),
    "whatsapp_inbox":            ("chat", ["user_scope_id", "username"]),
    "write_file":                ("chat", ["_session_id", "_session_workspace", "user_role", "user_scope_id"]),
}


IDENTITY_KEYS = {"user_scope_id", "username", "user_role"}
PLUMBING_KEYS = {"_agent", "_session_id", "session_id", "_session_workspace",
                 "_is_channel_session", "with_vaf_tools"}


def _stub_for(orig):
    """A tool that records instead of acting, wearing the real one's declarations.

    The schema matters: `repair_tool_input` rejects a call with missing required fields
    BEFORE the injection stage, so a stub with an empty schema would measure nothing.
    """
    class _Stub(BaseTool):
        name = orig.name
        description = getattr(orig, "description", "stub")
        parameters = getattr(orig, "parameters", {"type": "object", "properties": {}})
        identity_kwargs = getattr(orig, "identity_kwargs", ())
        permission_level = getattr(orig, "permission_level", "read")
        admin_only = getattr(orig, "admin_only", False)
        channel_restrictions = getattr(orig, "channel_restrictions", ())
        input_aliases = getattr(orig, "input_aliases", {})

        def __init__(self):
            super().__init__()
            self.seen = None

        def run(self, **kwargs):
            self.seen = dict(kwargs)
            return "STUB_OK"

    return _Stub()


def _required_args(schema):
    """Plausible values for the required fields, so the call reaches the injection stage."""
    schema = schema or {}
    props = schema.get("properties") or {}
    out = {}
    for field in schema.get("required") or []:
        spec = props.get(field) or {}
        t = spec.get("type")
        if isinstance(t, list):
            t = t[0]
        if spec.get("enum"):
            out[field] = spec["enum"][0]
        elif t == "integer":
            out[field] = 1
        elif t == "number":
            out[field] = 1.0
        elif t == "boolean":
            out[field] = False
        elif t == "array":
            out[field] = []
        elif t == "object":
            out[field] = {}
        else:
            out[field] = "probe"
    return out




def _fake_agent(tools, *, thinking=False):
    """The fixed context described in the module docstring. Every attribute here is one the
    dispatcher reads; validated against a real Agent over all 117 tools with 0 differences."""
    return bind_chat_stages(SimpleNamespace(
        tools=tools,
        _event_sink=None,
        _allow_once_tools=set(tools),
        _noninteractive=True,
        _current_turn_thinking_mode=thinking,
        _current_chat_source="web",
        current_session_id=None,
        _current_user_scope_id=SCOPE,
        _current_user_role="admin",
        _current_username="tenant",
        _run_kind="chat",
        _ww_training=False,
        _active_tools=set(),
        _turn_ran_progress_tool=False,
        _session_workspace=None,
        history=[],
        main_persistence=None,
        _record_tool_used=lambda name: None,
        _plan_gate_decision=lambda name, tool, tool_args=None: None,
        _working_memory_note_gate=lambda tool_args: None,
        _proactive_reply_gate_decision=lambda name, tool, args: None,
        _ask_first_gate_decision=lambda name, tool: None,
        get_live_session_subagents=lambda: [],
        _extract_subagent_goal=lambda args: "",
        model_display_name="probe",
    ))


def _all_tool_classes():
    import importlib
    import inspect
    import pkgutil

    import vaf.core
    import vaf.tools
    seen = {}
    for pkg in (vaf.tools, vaf.core):
        for m in pkgutil.iter_modules(pkg.__path__, pkg.__name__ + "."):
            try:
                mod = importlib.import_module(m.name)
            except Exception:
                continue
            for _, obj in inspect.getmembers(mod, inspect.isclass):
                if issubclass(obj, BaseTool) and obj is not BaseTool and getattr(obj, "name", None):
                    seen[obj.name] = obj
    return seen


TOOL_CLASSES = _all_tool_classes()


def _measure(tool_name, context):
    cls = TOOL_CLASSES[tool_name]
    stub = _stub_for(cls)
    model_args = _required_args(getattr(cls, "parameters", None))
    fake = _fake_agent({tool_name: stub}, thinking=(context == "thinking"))
    with patch("vaf.core.trust.get_tool_policy", return_value="always"), \
         patch("vaf.core.trust.is_trusted_dir", return_value=True):
        result = Agent.execute_tool(fake, tool_name, dict(model_args))
    assert stub.seen is not None, f"{tool_name} never ran; dispatcher returned {result[:120]!r}"
    return sorted(set(stub.seen) - set(model_args))


@pytest.mark.parametrize("tool_name", sorted(KWARGS_BASELINE))
def test_each_tool_still_receives_exactly_what_it_received_before(tool_name):
    """THE guard. Run per tool so a failure names the tool instead of dumping 117 rows."""
    if tool_name not in TOOL_CLASSES:
        pytest.fail(f"{tool_name} no longer resolves to a tool class")
    context, expected = KWARGS_BASELINE[tool_name]
    assert _measure(tool_name, context) == sorted(expected)


def test_no_tool_appeared_that_the_baseline_does_not_know():
    """A new tool is fine, but it must be measured into the baseline deliberately - otherwise
    the guard silently stops covering it."""
    known = set(KWARGS_BASELINE)
    missing = sorted(set(TOOL_CLASSES) - known)
    assert not missing, (
        f"tools with no baseline entry: {missing}. Measure them and add the rows; do not "
        f"type them."
    )


def test_the_baseline_only_contains_keys_the_dispatcher_can_actually_supply():
    """Catches a typo in the frozen literal itself - a misspelled key would make the row
    unfalsifiable, since the dispatcher would never produce it either."""
    allowed = IDENTITY_KEYS | PLUMBING_KEYS
    bad = {n: sorted(set(v) - allowed) for n, (_c, v) in KWARGS_BASELINE.items()
           if set(v) - allowed}
    assert not bad, f"baseline names keys the dispatcher never injects: {bad}"


def test_the_plumbing_split_is_visible_and_not_empty():
    """The split this refactor turns on: identity is declarative already, plumbing is still a
    hardcoded name cascade. If plumbing ever measures empty, the harness stopped reaching the
    cascade and every row above became vacuously true."""
    plumbed = {n for n, (_c, v) in KWARGS_BASELINE.items() if set(v) & PLUMBING_KEYS}
    identified = {n for n, (_c, v) in KWARGS_BASELINE.items() if set(v) & IDENTITY_KEYS}
    assert plumbed, "no tool receives plumbing - the harness is not reaching the cascade"
    assert identified, "no tool receives identity - the harness is not reaching the injection"
