# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""Frozen record of what one dispatch CHANGES outside its return value.

Third and last of the baselines taken before `execute_tool` is split. The first covers
what reaches a tool, the second what is emitted and returned. This one covers the writes:
process environment, the persistent trust store, the turn's allow-once set, and the router's
tool sets. They are the part of a refactor nobody diffs, because they are invisible in the
result.

Not measured here, and named so the list does not read as complete: a dispatch also appends
one line to `tool_use_<date>.log` (`ToolCaller._audit_log`, pinned by
tests/test_tool_use_audit_log.py). Files in the log directory were outside this baseline
when it was frozen, and widening a frozen measurement after the fact would make it a record
of two different moments.

WHAT THIS IS REALLY FOR - the asymmetry of `_record_tool_used`. There are 23 `return`
statements before the recording line, so a dispatch that ends early never updates the
router's recency. Measured, that is not arbitrary:

    recorded      ok, invalid_args, unknown_tool, dup_guard, search_tools, both gate accepts
    NOT recorded  a policy block, the plan gate, a refused confirmation

So an argument error counts as "the model tried this tool" while a policy block does not.
Whether or not that is the ideal rule, it is the current one, and a funnel that records once
at the end - the obvious shape - would silently start counting blocked tools as used, which
changes what the router offers on the next turn. Nothing about that shows up in a test that
only checks return values.

THE OTHER THREE:

- `os.environ["VAF_SESSION_ID"]` is written on NO path any more, and the baseline records
  that as False everywhere. It used to be written on every path that resolved a session
  id, including blocked ones, because the write happened before policy ran. The
  justification recorded here - "the workflow CLI subprocess READS this variable, which is
  why it must stay in the chat wrapper" - was already stale when it was written: the
  workflow spawn puts the id into the CHILD's env explicitly (`agent.py`, "not the
  parent's global env"), and `Platform.open_new_terminal` merges that over
  `os.environ.copy()`, so the explicit value wins. Meanwhile the parent-side write was a
  process-global mutation that nothing restored, in a process where the chat worker,
  thinking and the automation scheduler all dispatch tools on their own threads. A lane
  that needs the session now asks `subagent_ipc.get_current_session_id()`, which answers
  per context.
- The trust store is written on exactly one path: accepting a gate with "always"
  (`mark_trusted_dir` + `set_tool_policy`). That write outlives the process and is
  machine-global, so moving the gate is the single riskiest step of the split.
- `_allow_once_tools` grows only on the "once" answer, and `_active_tools` only through the
  search_tools post-hook - which parses one tool per line, name before the colon, and
  silently yields nothing for any other shape.

Measured, never typed. Five measurement bugs were caught and fixed while building these
baselines rather than frozen into them; the search_tools output format was the last of them.
"""
import os
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from conftest import bind_chat_stages
from vaf.core.agent import Agent
from vaf.tools.base import BaseTool

SCOPE = "deadbeef-0000-0000-0000-000000000000"   # synthetic; never a real scope UUID
_LIVE_CODER = [{"agent_type": "coding_agent", "task_description": "t", "running_seconds": 60}]
_STRICT = {"type": "object", "properties": {"x": {"type": "string"}}, "required": ["x"]}


# Generated by measurement against the unchanged dispatcher - never edit by hand.
SIDE_EFFECT_BASELINE = {
    "dup_guard": {
        "env_session_id_written": False,
        "recorded_tool_use": ['coding_agent'],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "gate_allow_always": {
        "env_session_id_written": False,
        "recorded_tool_use": ['probe'],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": ['mark_trusted_dir', 'set_tool_policy'],
    },
    "gate_allow_once": {
        "env_session_id_written": False,
        "recorded_tool_use": ['probe'],
        "allow_once_added": ['probe'],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "gate_refused": {
        "env_session_id_written": False,
        "recorded_tool_use": [],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "invalid_args": {
        "env_session_id_written": False,
        "recorded_tool_use": ['probe'],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "ok": {
        "env_session_id_written": False,
        "recorded_tool_use": ['probe'],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "plan_gate": {
        "env_session_id_written": False,
        "recorded_tool_use": [],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "policy_admin_only": {
        "env_session_id_written": False,
        "recorded_tool_use": [],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
    "search_tools": {
        "env_session_id_written": False,
        "recorded_tool_use": ['search_tools'],
        "allow_once_added": [],
        "active_tools_added": ['read_file', 'write_file'],
        "trust_writes": [],
    },
    "unknown_tool": {
        "env_session_id_written": False,
        "recorded_tool_use": ['nope'],
        "allow_once_added": [],
        "active_tools_added": [],
        "trust_writes": [],
    },
}


class _Probe(BaseTool):
    name = "probe"
    description = "probe"
    permission_level = "read"
    parameters = {"type": "object", "properties": {"x": {"type": "string"}}}

    def __init__(self, fn=None, **attrs):
        super().__init__()
        self._fn = fn or (lambda **kw: "OK")
        for k, v in attrs.items():
            setattr(self, k, v)

    def run(self, **kwargs):
        return self._fn(**kwargs)


def _tool(name, fn=None, **attrs):
    t = _Probe(fn, **attrs)
    t.name = name
    return t




def _probe(tools, call, pre_approved=True, **over):
    """Run one dispatch and report only what it changed around itself."""
    recorded, trust_writes = [], []
    pre_allowed = {t.name for t in tools} if pre_approved else set()
    base = dict(
        tools={t.name: t for t in tools}, _event_sink=None,
        _allow_once_tools=set(pre_allowed), _noninteractive=True,
        _current_turn_thinking_mode=False, _current_chat_source="web",
        current_session_id="probe-session", _current_user_scope_id=SCOPE,
        _current_user_role="admin", _current_username="tenant", _run_kind="chat",
        _ww_training=False, _active_tools=set(), _turn_ran_progress_tool=False,
        _session_workspace=None, history=[], main_persistence=None,
        _record_tool_used=recorded.append,
        _plan_gate_decision=lambda n, t, tool_args=None: None,
        _working_memory_note_gate=lambda tool_args: None,
        _proactive_reply_gate_decision=lambda n, t, a: None,
        _ask_first_gate_decision=lambda n, t: None,
        get_live_session_subagents=lambda: [], _extract_subagent_goal=lambda a: "",
        model_display_name="probe",
    )
    base.update(over)
    fake = bind_chat_stages(SimpleNamespace(**base))

    env_before = os.environ.get("VAF_SESSION_ID", "<unset>")
    policy = "always" if pre_approved else "ask"
    try:
        with patch("vaf.core.trust.get_tool_policy", return_value=policy), \
             patch("vaf.core.trust.is_trusted_dir", return_value=pre_approved), \
             patch("vaf.core.trust.set_tool_policy",
                   lambda *a: trust_writes.append("set_tool_policy")), \
             patch("vaf.core.trust.mark_trusted_dir",
                   lambda *a: trust_writes.append("mark_trusted_dir")):
            Agent.execute_tool(fake, *call)
        env_after = os.environ.get("VAF_SESSION_ID", "<unset>")
    finally:
        # Never leak the probe's session id into the rest of the suite.
        if env_before == "<unset>":
            os.environ.pop("VAF_SESSION_ID", None)
        else:
            os.environ["VAF_SESSION_ID"] = env_before
    return {
        "env_session_id_written": env_after != env_before,
        "recorded_tool_use": list(recorded),
        "allow_once_added": sorted(fake._allow_once_tools - pre_allowed),
        "active_tools_added": sorted(fake._active_tools),
        "trust_writes": sorted(set(trust_writes)),
    }


def _gate(answer):
    """The interactive gate, answered. The only path that writes the persistent store."""
    dangerous = _tool("probe", permission_level="dangerous")
    with patch("vaf.cli.ui.UI.prompt", return_value=answer), \
         patch("vaf.cli.ui.UI.event", lambda *a, **k: None):
        return _probe([dangerous], ("probe", {}), pre_approved=False,
                      _noninteractive=False, current_session_id=None)


SCENARIOS = {
    "ok": lambda: _probe([_tool("probe")], ("probe", {})),
    "unknown_tool": lambda: _probe([_tool("probe")], ("nope", {})),
    "invalid_args": lambda: _probe([_tool("probe", parameters=_STRICT)], ("probe", {})),
    "policy_admin_only": lambda: _probe([_tool("probe", admin_only=True)], ("probe", {}),
                                        _current_user_role="user"),
    "plan_gate": lambda: _probe(
        [_tool("probe")], ("probe", {}),
        _plan_gate_decision=lambda n, t, tool_args=None: "[PLAN REQUIRED] x"),
    "gate_refused": lambda: _probe([_tool("probe", permission_level="dangerous")],
                                   ("probe", {}), pre_approved=False),
    "dup_guard": lambda: _probe([_tool("coding_agent")], ("coding_agent", {}),
                                get_live_session_subagents=lambda: _LIVE_CODER),
    "search_tools": lambda: _probe(
        [_tool("search_tools",
               lambda **kw: "- write_file: writes a file\n- read_file: reads a file"),
         _tool("write_file"), _tool("read_file")], ("search_tools", {})),
    "gate_allow_always": lambda: _gate("a"),
    "gate_allow_once": lambda: _gate("o"),
}


@pytest.mark.parametrize("scenario", sorted(SIDE_EFFECT_BASELINE))
def test_the_side_effects_of_a_dispatch_are_unchanged(scenario):
    assert scenario in SCENARIOS, f"{scenario} is frozen but has no way to reproduce it"
    assert SCENARIOS[scenario]() == SIDE_EFFECT_BASELINE[scenario]


def test_every_scenario_is_frozen():
    missing = sorted(set(SCENARIOS) - set(SIDE_EFFECT_BASELINE))
    assert not missing, f"scenarios with no frozen result: {missing}"


def test_a_blocked_tool_does_not_count_as_used():
    """The asymmetry, spelled out: recording once at the end of a funnel - the obvious
    shape - would start counting blocked tools as used and change what the router offers
    next turn."""
    for blocked in ("policy_admin_only", "plan_gate", "gate_refused"):
        assert SIDE_EFFECT_BASELINE[blocked]["recorded_tool_use"] == [], blocked
    for used in ("ok", "invalid_args", "unknown_tool"):
        assert SIDE_EFFECT_BASELINE[used]["recorded_tool_use"] != [], used


def test_only_one_path_writes_the_persistent_trust_store():
    """That write outlives the process and is machine-global, so the gate is the riskiest
    piece to move. Any second path acquiring it is a finding, not a detail."""
    writers = sorted(n for n, v in SIDE_EFFECT_BASELINE.items() if v["trust_writes"])
    assert writers == ["gate_allow_always"], writers
    assert SIDE_EFFECT_BASELINE["gate_allow_always"]["trust_writes"] == [
        "mark_trusted_dir", "set_tool_policy"]
    assert SIDE_EFFECT_BASELINE["gate_allow_once"]["trust_writes"] == [], (
        "answering 'once' must stay in memory - persisting it would silently widen a "
        "single approval into a standing one"
    )
