# SPDX-FileCopyrightText: 2026 Veyllo GmbH
# SPDX-License-Identifier: AGPL-3.0-or-later
# Additional permissions and terms under AGPL Section 7: see LICENSING.md
"""
VAF Speech Fillers
Multilingual filler phrases for natural TTS feedback during thinking and tool execution.
"""

# Thinking fillers: Natural, helpful assistant style
THINKING_FILLERS = {
    "de": [
        "Einen kleinen Moment.",
        "Moment bitte.",
        "Einen Augenblick.",
        "Einen Moment bitte.",
        "Okay kleinen Augenblick.",
        "Okay, Moment.",
        "Kleinen Moment bitte.",
        "Kurzen Moment bitte.",
        "Einen Augenblick bitte.",
        "Eine Sekunde bitte."
        
    ],
    "en": [
        "Just a moment",
        "One moment please",
        "Give me a second",
        "Alright, let me check",
        "Okay, one sec",
        "Got it, let me look into that",
        "Sure, just a moment",
        "Let me see here",
        "Okay, checking now",
        "Right, give me a second",
        "Let me take a quick look"
    ],
    "tr": [
        "Bir saniye",
        "Bir dakika",
        "Tamam, bir bakayım",
        "Anladım, hemen bakıyorum",
        "Peki, bir saniye",
        "Hemen kontrol ediyorum",
        "Tamam, bakıyorum",
        "Şimdi bakayım",
        "Bir bakalım",
        "Hemen bir göz atayım",
        "Kontrol edeyim"
    ],
    "es": [
        "Un momento",
        "Dame un segundo",
        "Vale, déjame ver",
        "Entendido, lo reviso",
        "Okay, un momento",
        "Déjame comprobar eso",
        "Bien, un segundo",
        "Voy a mirar",
        "Déjame ver aquí",
        "Vale, revisando",
        "Un momento por favor"
    ],
    "fr": [
        "Un instant",
        "Une seconde",
        "D'accord, laisse-moi voir",
        "Compris, je vérifie",
        "Okay, un moment",
        "Je regarde ça",
        "Bien, une seconde",
        "Laisse-moi vérifier",
        "Je jette un œil",
        "D'accord, je regarde",
        "Un instant s'il te plaît"
    ],
    "it": [
        "Un attimo",
        "Un secondo",
        "Va bene, fammi vedere",
        "Capito, controllo subito",
        "Okay, un momento",
        "Lasciami controllare",
        "Bene, un secondo",
        "Vediamo qui",
        "Controllo adesso",
        "D'accordo, un attimo",
        "Fammi dare un'occhiata"
    ],
    "ru": [
        "Минутку",
        "Секунду",
        "Хорошо, сейчас посмотрю",
        "Понял, проверяю",
        "Окей, момент",
        "Сейчас проверю",
        "Хорошо, секунду",
        "Посмотрю сейчас",
        "Проверяю",
        "Дай секунду",
        "Сейчас гляну"
    ],
    "ja": [
        "ちょっと待って",
        "少々お待ちください",
        "わかりました、確認します",
        "了解、ちょっと見ます",
        "はい、一瞬で",
        "確認してみます",
        "ちょっと調べます",
        "見てみますね",
        "すぐ確認します",
        "ちょっと見てみます",
        "確認中です"
    ],
    "zh": [
        "稍等一下",
        "等一下",
        "好的，让我看看",
        "明白了，我查一下",
        "好，稍等",
        "我查查看",
        "让我确认一下",
        "我看看",
        "正在查",
        "等我一下",
        "我看一眼"
    ],
    "pt": [
        "Um momento",
        "Só um segundo",
        "Certo, deixa eu ver",
        "Entendi, vou verificar",
        "Okay, um momento",
        "Deixa eu checar isso",
        "Beleza, um segundo",
        "Vou dar uma olhada",
        "Deixa eu ver aqui",
        "Tá, verificando",
        "Deixa eu conferir"
    ],
    "nl": [
        "Een momentje",
        "Even geduld",
        "Oké, laat me kijken",
        "Begrepen, ik check het",
        "Okay, momentje",
        "Laat me dat checken",
        "Goed, een seconde",
        "Even kijken hier",
        "Ik kijk even",
        "Oké, aan het checken",
        "Laat me even zien"
    ],
    "pl": [
        "Chwileczkę",
        "Sekundę",
        "Dobra, sprawdzę",
        "Rozumiem, sprawdzam",
        "Okej, moment",
        "Sprawdzę to",
        "Dobrze, sekunda",
        "Zobaczmy",
        "Sprawdzam teraz",
        "Okej, patrzę",
        "Zaraz sprawdzę"
    ],
    "sv": [
        "Ett ögonblick",
        "En sekund",
        "Okej, låt mig kolla",
        "Förstår, jag kollar",
        "Okej, ett moment",
        "Låt mig kolla det",
        "Bra, en sekund",
        "Låt mig se här",
        "Kollar nu",
        "Okej, kollar",
        "Låt mig titta"
    ],
    "ar": [
        "لحظة واحدة",
        "ثانية واحدة",
        "حسناً، دعني أتحقق",
        "فهمت، سأفحص",
        "حسناً، لحظة",
        "دعني أفحص ذلك",
        "جيد، ثانية",
        "دعني أنظر",
        "أتحقق الآن",
        "حسناً، أنظر",
        "سأتحقق بسرعة"
    ],
    "hi": [
        "एक पल",
        "एक सेकंड",
        "ठीक है, मुझे देखने दो",
        "समझ गया, मैं चेक करता हूं",
        "ओके, एक पल",
        "मुझे चेक करने दो",
        "अच्छा, एक सेकंड",
        "देखता हूं",
        "अभी चेक कर रहा हूं",
        "ठीक है, देख रहा हूं",
        "जल्दी से देखता हूं"
    ]
}

# Tool-specific fillers: Context-aware feedback
TOOL_FILLERS = {
    "web_search": {
        "de": "Ich suche im Internet nach {query}",
        "en": "Searching the web for {query}",
        "tr": "İnternette {query} arıyorum",
        "es": "Buscando en internet {query}",
        "fr": "Je recherche {query} sur internet",
        "it": "Sto cercando {query} su internet",
        "ru": "Ищу в интернете {query}",
        "ja": "{query}をウェブで検索しています",
        "zh": "正在网上搜索{query}",
        "pt": "Procurando na internet por {query}",
        "nl": "Ik zoek op internet naar {query}",
        "pl": "Szukam w internecie {query}",
        "sv": "Söker på internet efter {query}",
        "ar": "أبحث في الإنترنت عن {query}",
        "hi": "इंटरनेट पर {query} खोज रहा हूं"
    },
    "coding_agent": {
        "de": "Ich erstelle den Code für dich",
        "en": "Creating the code for you",
        "tr": "Senin için kod oluşturuyorum",
        "es": "Creando el código para ti",
        "fr": "Je crée le code pour toi",
        "it": "Sto creando il codice per te",
        "ru": "Создаю код для тебя",
        "ja": "コードを作成しています",
        "zh": "正在为你创建代码",
        "pt": "Criando o código para você",
        "nl": "Ik maak de code voor je",
        "pl": "Tworzę kod dla ciebie",
        "sv": "Skapar koden åt dig",
        "ar": "أنشئ الكود لك",
        "hi": "आपके लिए कोड बना रहा हूं"
    },
    "research_agent": {
        "de": "Ich recherchiere das für dich",
        "en": "Researching that for you",
        "tr": "Senin için araştırıyorum",
        "es": "Investigando eso para ti",
        "fr": "Je fais des recherches pour toi",
        "it": "Sto facendo ricerche per te",
        "ru": "Исследую это для тебя",
        "ja": "調査しています",
        "zh": "正在为你研究",
        "pt": "Pesquisando isso para você",
        "nl": "Ik doe onderzoek voor je",
        "pl": "Badam to dla ciebie",
        "sv": "Forskar åt dig",
        "ar": "أبحث عن ذلك لك",
        "hi": "आपके लिए शोध कर रहा हूं"
    },
    "read_file": {
        "de": "Ich lese die Datei",
        "en": "Reading the file",
        "tr": "Dosyayı okuyorum",
        "es": "Leyendo el archivo",
        "fr": "Je lis le fichier",
        "it": "Sto leggendo il file",
        "ru": "Читаю файл",
        "ja": "ファイルを読んでいます",
        "zh": "正在读取文件",
        "pt": "Lendo o arquivo",
        "nl": "Ik lees het bestand",
        "pl": "Czytam plik",
        "sv": "Läser filen",
        "ar": "أقرأ الملف",
        "hi": "फ़ाइल पढ़ रहा हूं"
    },
    "write_file": {
        "de": "Ich schreibe die Datei",
        "en": "Writing the file",
        "tr": "Dosyayı yazıyorum",
        "es": "Escribiendo el archivo",
        "fr": "J'écris le fichier",
        "it": "Sto scrivendo il file",
        "ru": "Записываю файл",
        "ja": "ファイルを書き込んでいます",
        "zh": "正在写入文件",
        "pt": "Escrevendo o arquivo",
        "nl": "Ik schrijf het bestand",
        "pl": "Zapisuję plik",
        "sv": "Skriver filen",
        "ar": "أكتب الملف",
        "hi": "फ़ाइल लिख रहा हूं"
    },
    "bash": {
        "de": "Ich führe den Befehl aus",
        "en": "Running the command",
        "tr": "Komutu çalıştırıyorum",
        "es": "Ejecutando el comando",
        "fr": "J'exécute la commande",
        "it": "Sto eseguendo il comando",
        "ru": "Выполняю команду",
        "ja": "コマンドを実行しています",
        "zh": "正在运行命令",
        "pt": "Executando o comando",
        "nl": "Ik voer het commando uit",
        "pl": "Wykonuję polecenie",
        "sv": "Kör kommandot",
        "ar": "أنفذ الأمر",
        "hi": "कमांड चला रहा हूं"
    },
    "python_exec": {
        "de": "Ich führe den Python-Code aus",
        "en": "Running the Python code",
        "tr": "Python kodunu çalıştırıyorum",
        "es": "Ejecutando el código Python",
        "fr": "J'exécute le code Python",
        "it": "Sto eseguendo il codice Python",
        "ru": "Выполняю Python код",
        "ja": "Pythonコードを実行しています",
        "zh": "正在运行Python代码",
        "pt": "Executando o código Python",
        "nl": "Ik voer de Python-code uit",
        "pl": "Wykonuję kod Python",
        "sv": "Kör Python-koden",
        "ar": "أنفذ كود Python",
        "hi": "Python कोड चला रहा हूं"
    },
    "webfetch": {
        "de": "Ich rufe die Webseite auf",
        "en": "Accessing the website",
        "tr": "Web sitesine erişiyorum",
        "es": "Accediendo al sitio web",
        "fr": "J'accède au site web",
        "it": "Accesso al sito web",
        "ru": "Открываю веб-сайт",
        "ja": "ウェブサイトにアクセスしています",
        "zh": "正在访问网站",
        "pt": "Acessando o site",
        "nl": "Ik open de website",
        "pl": "Otwieram stronę internetową",
        "sv": "Öppnar webbplatsen",
        "ar": "جارٍ الوصول إلى الموقع",
        "hi": "वेबसाइट खोल रहा हूं"
    }
}
