"""
VAF Scaffold - Create Project Templates
Automated project structure for various languages/frameworks
"""
import typer
import os
from pathlib import Path
from datetime import datetime
from vaf.cli.ui import UI

app = typer.Typer()

# ═══════════════════════════════════════════════════════════════════════════════
# PROJECT TEMPLATE DEFINITIONS
# ═══════════════════════════════════════════════════════════════════════════════

TEMPLATES = {
    "python": {
        "description": "Python project with best practices",
        "files": {
            "main.py": '''"""
{project_name} - Main Entry Point
Generated by VAF Scaffold
"""

def main():
    """Main function."""
    print("Hello from {project_name}!")

if __name__ == "__main__":
    main()
''',
            "requirements.txt": '''# {project_name} Dependencies
# Generated by VAF Scaffold on {date}

# Core
# requests>=2.28.0

# Development
# pytest>=7.0.0
# black>=23.0.0
''',
            "README.md": '''# {project_name}

> Generated by VAF Scaffold

## Installation

```bash
pip install -r requirements.txt
```

## Usage

```bash
python main.py
```

## License

MIT
''',
            ".gitignore": '''# Python
__pycache__/
*.py[cod]
*$py.class
*.so
.Python
venv/
ENV/
.env
*.egg-info/
dist/
build/

# IDE
.vscode/
.idea/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db
''',
            "src/__init__.py": '''"""
{project_name} Package
"""
__version__ = "0.1.0"
''',
            "tests/__init__.py": '''"""Tests for {project_name}"""
''',
            "tests/test_main.py": '''"""
Tests for main module
"""
import pytest

def test_placeholder():
    """Placeholder test."""
    assert True
''',
        }
    },
    
    "python-flask": {
        "description": "Flask Web API project",
        "files": {
            "app.py": '''"""
{project_name} - Flask Application
Generated by VAF Scaffold
"""
from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def index():
    return jsonify({{"message": "Welcome to {project_name}!"}})

@app.route("/health")
def health():
    return jsonify({{"status": "healthy"}})

if __name__ == "__main__":
    app.run(debug=True, port=5000)
''',
            "requirements.txt": '''# {project_name} Dependencies
flask>=3.0.0
python-dotenv>=1.0.0
gunicorn>=21.0.0
''',
            "README.md": '''# {project_name}

> Flask Web API - Generated by VAF Scaffold

## Installation

```bash
pip install -r requirements.txt
```

## Development

```bash
python app.py
```

## Production

```bash
gunicorn app:app
```

## API Endpoints

- `GET /` - Welcome message
- `GET /health` - Health check
''',
            ".env.example": '''# Environment Variables
FLASK_ENV=development
SECRET_KEY=your-secret-key
''',
            ".gitignore": '''__pycache__/
*.py[cod]
venv/
.env
*.log
''',
        }
    },
    
    "javascript": {
        "description": "Node.js project",
        "files": {
            "index.js": '''/**
 * {project_name}
 * Generated by VAF Scaffold
 */

console.log("Hello from {project_name}!");

module.exports = {
    name: "{project_name}",
    version: "1.0.0"
};
''',
            "package.json": '''{
    "name": "{project_name_lower}",
    "version": "1.0.0",
    "description": "Generated by VAF Scaffold",
    "main": "index.js",
    "scripts": {
        "start": "node index.js",
        "dev": "node --watch index.js",
        "test": "echo \\"No tests yet\\" && exit 0"
    },
    "keywords": [],
    "author": "",
    "license": "MIT"
}
''',
            "README.md": '''# {project_name}

> Node.js Project - Generated by VAF Scaffold

## Installation

```bash
npm install
```

## Usage

```bash
npm start
```

## Development

```bash
npm run dev
```
''',
            ".gitignore": '''node_modules/
.env
*.log
dist/
.DS_Store
''',
        }
    },
    
    "typescript": {
        "description": "TypeScript project",
        "files": {
            "src/index.ts": '''/**
 * {project_name}
 * Generated by VAF Scaffold
 */

interface AppConfig {
    name: string;
    version: string;
}

const config: AppConfig = {
    name: "{project_name}",
    version: "1.0.0"
};

console.log(`Hello from ${config.name}!`);

export default config;
''',
            "package.json": '''{
    "name": "{project_name_lower}",
    "version": "1.0.0",
    "description": "Generated by VAF Scaffold",
    "main": "dist/index.js",
    "scripts": {
        "build": "tsc",
        "start": "node dist/index.js",
        "dev": "ts-node src/index.ts",
        "test": "echo \\"No tests yet\\" && exit 0"
    },
    "devDependencies": {
        "typescript": "^5.0.0",
        "ts-node": "^10.9.0",
        "@types/node": "^20.0.0"
    }
}
''',
            "tsconfig.json": '''{
    "compilerOptions": {
        "target": "ES2020",
        "module": "commonjs",
        "lib": ["ES2020"],
        "outDir": "./dist",
        "rootDir": "./src",
        "strict": true,
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true,
        "resolveJsonModule": true
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules", "dist"]
}
''',
            "README.md": '''# {project_name}

> TypeScript Project - Generated by VAF Scaffold

## Installation

```bash
npm install
```

## Build

```bash
npm run build
```

## Development

```bash
npm run dev
```
''',
            ".gitignore": '''node_modules/
dist/
.env
*.log
.DS_Store
''',
        }
    },
    
    "rust": {
        "description": "Rust project (Cargo)",
        "files": {
            "Cargo.toml": '''[package]
name = "{project_name_lower}"
version = "0.1.0"
edition = "2021"
description = "Generated by VAF Scaffold"

[dependencies]

[dev-dependencies]
''',
            "src/main.rs": '''//! {project_name}
//! Generated by VAF Scaffold

fn main() {
    println!("Hello from {project_name}!");
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
''',
            "README.md": '''# {project_name}

> Rust Project - Generated by VAF Scaffold

## Build

```bash
cargo build
```

## Run

```bash
cargo run
```

## Test

```bash
cargo test
```
''',
            ".gitignore": '''target/
Cargo.lock
*.pdb
''',
        }
    },
    
    "go": {
        "description": "Go project",
        "files": {
            "main.go": '''// {project_name}
// Generated by VAF Scaffold
package main

import "fmt"

func main() {
	fmt.Println("Hello from {project_name}!")
}
''',
            "go.mod": '''module {project_name_lower}

go 1.21
''',
            "README.md": '''# {project_name}

> Go Project - Generated by VAF Scaffold

## Build

```bash
go build
```

## Run

```bash
go run .
```

## Test

```bash
go test ./...
```
''',
            ".gitignore": '''# Binaries
*.exe
*.exe~
*.dll
*.so
*.dylib
{project_name_lower}

# Test binary
*.test

# Output
*.out

# Dependency directories
vendor/
''',
        }
    },
    
    "html": {
        "description": "Static HTML website",
        "files": {
            "index.html": '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name}</title>
    <link rel="stylesheet" href="css/style.css">
</head>
<body>
    <header>
        <nav>
            <h1>{project_name}</h1>
        </nav>
    </header>
    
    <main>
        <section class="hero">
            <h2>Welcome!</h2>
            <p>This page was created with VAF Scaffold.</p>
        </section>
    </main>
    
    <footer>
        <p>&copy; {year} {project_name}</p>
    </footer>
    
    <script src="js/main.js"></script>
</body>
</html>
''',
            "css/style.css": '''/* {project_name} Styles */
/* Generated by VAF Scaffold */

:root {
    --primary: #3b82f6;
    --background: #0f172a;
    --surface: #1e293b;
    --text: #f8fafc;
    --text-muted: #94a3b8;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: system-ui, -apple-system, sans-serif;
    background: var(--background);
    color: var(--text);
    line-height: 1.6;
    min-height: 100vh;
}

header {
    background: var(--surface);
    padding: 1rem 2rem;
    border-bottom: 1px solid rgba(255,255,255,0.1);
}

header h1 {
    color: var(--primary);
}

main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 2rem;
}

.hero {
    text-align: center;
    padding: 4rem 2rem;
}

.hero h2 {
    font-size: 2.5rem;
    margin-bottom: 1rem;
}

.hero p {
    color: var(--text-muted);
    font-size: 1.2rem;
}

footer {
    text-align: center;
    padding: 2rem;
    color: var(--text-muted);
    border-top: 1px solid rgba(255,255,255,0.1);
}
''',
            "js/main.js": '''/**
 * {project_name} - JavaScript
 * Generated by VAF Scaffold
 */

document.addEventListener('DOMContentLoaded', () => {
    console.log('{project_name} loaded!');
});
''',
            "README.md": '''# {project_name}

> Static HTML Website - Generated by VAF Scaffold

## Structure

```
{project_name}/
├── index.html
├── css/
│   └── style.css
├── js/
│   └── main.js
└── README.md
```

## Development

Open `index.html` in your browser, or use a local server:

```bash
# Python
python -m http.server 8000

# Node.js
npx serve
```
''',
        }
    },
}

# ═══════════════════════════════════════════════════════════════════════════════
# SCAFFOLD COMMANDS
# ═══════════════════════════════════════════════════════════════════════════════

@app.command("list")
def list_templates():
    """Show all available project templates."""
    UI.panel("Available Project Templates", style="cyan")
    
    for name, template in TEMPLATES.items():
        UI.print(f"  [bold cyan]{name:<15}[/bold cyan] - {template['description']}")
    
    UI.print()
    UI.print("[dim]Usage: vaf scaffold new <template> <projectname>[/dim]")

@app.command("new")
def create_project(
    template: str = typer.Argument(..., help="Template name (e.g. python, javascript)"),
    name: str = typer.Argument(..., help="Project name"),
    path: str = typer.Option(".", "--path", "-p", help="Target directory")
):
    """
    Create a new project from a template.
    
    Examples:
        vaf scaffold new python my-project
        vaf scaffold new typescript my-app --path ~/Projects
    """
    if template not in TEMPLATES:
        UI.error(f"Unknown template: {template}")
        UI.print(f"[dim]Available: {', '.join(TEMPLATES.keys())}[/dim]")
        raise typer.Exit(1)
    
    # Create project directory
    project_path = Path(path).expanduser() / name
    
    if project_path.exists():
        UI.error(f"Directory already exists: {project_path}")
        raise typer.Exit(1)
    
    UI.event("Scaffold", f"Creating {template} project: {name}", style="cyan")
    
    # Template variables
    variables = {
        "project_name": name,
        "project_name_lower": name.lower().replace(" ", "-").replace("_", "-"),
        "date": datetime.now().strftime("%Y-%m-%d"),
        "year": datetime.now().strftime("%Y"),
    }
    
    # Create files
    template_def = TEMPLATES[template]
    created_files = []
    
    for file_path, content in template_def["files"].items():
        full_path = project_path / file_path
        
        # Create directories
        full_path.parent.mkdir(parents=True, exist_ok=True)
        
        # Replace variables
        final_content = content
        for var, value in variables.items():
            final_content = final_content.replace(f"{{{var}}}", value)
        
        # Write file
        full_path.write_text(final_content, encoding="utf-8")
        created_files.append(file_path)
        UI.event("Create", f"  {file_path}", style="dim")
    
    # Summary
    UI.print()
    UI.success(f"Project created: {project_path}")
    UI.print(f"[dim]  {len(created_files)} files created[/dim]")
    UI.print()
    UI.print("[bold]Next steps:[/bold]")
    UI.print(f"  cd {name}")
    
    # Language-specific hints
    if template in ["python", "python-flask"]:
        UI.print("  pip install -r requirements.txt")
        UI.print("  python main.py" if template == "python" else "  python app.py")
    elif template in ["javascript", "typescript"]:
        UI.print("  npm install")
        UI.print("  npm start")
    elif template == "rust":
        UI.print("  cargo build")
        UI.print("  cargo run")
    elif template == "go":
        UI.print("  go build")
        UI.print("  go run .")
    elif template == "html":
        UI.print("  # Open index.html in your browser")

@app.callback(invoke_without_command=True)
def scaffold_callback(ctx: typer.Context):
    """
    VAF Scaffold - Create project templates.
    
    Automatically creates project structures for various languages.
    """
    if ctx.invoked_subcommand is None:
        list_templates()
